FROM node:20.5-alpine3.17 as web
WORKDIR /app
COPY web/package.json .
COPY web/pnpm-lock.yaml .
COPY web/.npmrc .
RUN npm i -g pnpm
RUN pnpm i --frozen-lockfile --ignore-scripts
COPY web/ .
RUN pnpm build

FROM debian:bullseye-slim
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*
COPY build/bin/defguard .
COPY --from=web /app/dist ./web
USER 1000
ENTRYPOINT ["./defguard"]
