version: "3"

services:
  core:
    image: ghcr.io/defguard/defguard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEFGUARD_LDAP_URL: ldap://openldap:1389
      DEFGUARD_LDAP_BIND_USERNAME: cn=user,ou=users,dc=example,dc=org
      DEFGUARD_LDAP_BIND_PASSWORD: user
      DEFGUARD_LDAP_USER_SEARCH_BASE: "ou=users,dc=example,dc=org"
      DEFGUARD_LDAP_GROUP_SEARCH_BASE: "ou=groups,dc=example,dc=org"
      DEFGUARD_AUTH_SECRET: defguard-auth-secret
      DEFGUARD_GATEWAY_SECRET: defguard-gateway-secret
      DEFGUARD_YUBIBRIDGE_SECRET: defguard-yubibridge-secret
      DEFGUARD_DB_HOST: db
      DEFGUARD_DB_PORT: 5432
      DEFGUARD_DB_USER: defguard
      DEFGUARD_DB_PASSWORD: defguard
      DEFGUARD_DB_NAME: defguard
      DEFGUARD_URL: http://localhost:3000
      RUST_BACKTRACE: 1
    ports:
      # rest api
      - "8000:8000"
      # grpc
      - "50055:50055"
    depends_on:
      - db

  gateway:
    image: ghcr.io/defguard/gateway:latest
    environment:
      DEFGUARD_GRPC_URL: http://core:50055
      DEFGUARD_STATS_PERIOD: 60
      DEFGUARD_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEZWZHdWFyZCIsInN1YiI6IlRlc3ROZXQiLCJjbGllbnRfaWQiOiIiLCJleHAiOjU5NjE3NDcwNzYsIm5iZiI6MTY2Njc3OTc4MSwicm9sZXMiOltdfQ.uEUMnw_gO23W0K2q3N1lToeP0D2zAY1swr8N-84sRHA
      RUST_LOG: debug
    ports:
      # wireguard endpoint
      - "50051:50051/udp"
    depends_on:
      - core
    cap_add:
      - NET_ADMIN

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: defguard
      POSTGRES_USER: defguard
      POSTGRES_PASSWORD: defguard
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  device:
    build:
      dockerfile: Dockerfile.device
      context: .
    depends_on:
      - gateway
    cap_add:
      - NET_ADMIN

  openldap:
    image: bitnami/openldap:2.6
    user: root
    restart: unless-stopped
    environment:
      LDAP_EXTRA_SCHEMAS: "cosine,inetorgperson,nis,openssh-lpk_openldap,samba,gnupg-ldap-schema,orion"
    ports:
      - "389:1389"
    volumes:
      - ./ldap-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./ldif/gnupg-ldap-schema.ldif:/opt/bitnami/openldap/etc/schema/gnupg-ldap-schema.ldif:ro
      - ./ldif/openssh-lpk_openldap.ldif:/opt/bitnami/openldap/etc/schema/openssh-lpk_openldap.ldif:ro
      - ./ldif/orion.ldif:/opt/bitnami/openldap/etc/schema/orion.ldif:ro
      - ./ldif/samba.ldif:/opt/bitnami/openldap/etc/schema/samba.ldif:ro
      - ./ldif/init.ldif:/ldifs/init.ldif:ro
      - ./ldif/custom.ldif:/schema/custom.ldif:ro
      - ./.volumes_ldap/openldap:/bitnami/openldap