services:
  core:
    image: ghcr.io/defguard/defguard:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEFGUARD_DB_HOST: db
      DEFGUARD_DB_PORT: 5432
      DEFGUARD_DB_USER: defguard
      DEFGUARD_DB_PASSWORD: defguard
      DEFGUARD_DB_NAME: defguard
      RUST_BACKTRACE: 1
    ports:
      # REST API
      - "8000:8000"
      # Default Core GRPC port
      - "50055:50055"
    depends_on:
      - db

  gateway:
    image: ghcr.io/defguard/gateway:${IMAGE_TAG}
    ports:
      # WireGuard endpoint
      - "50051:50051/udp"
      # Default Gateway GRPC port
      - "50066:50066"
    depends_on:
      - core
    cap_add:
      - NET_ADMIN

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: defguard
      POSTGRES_USER: defguard
      POSTGRES_PASSWORD: defguard
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # vector:
  #   image: timberio/vector:latest-alpine
  #   profiles:
  #     - observability
  #   container_name: vector
  #   volumes:
  #     - ./configs/vector.yaml:/etc/vector/vector.yaml:ro
  #     - ./configs/key.pem:/etc/vector/key.pem:ro
  #     - ./configs/cert.pem:/etc/vector/cert.pem:ro
  #   command: ["--config", "/etc/vector/vector.yaml"]
  #   ports:
  #     - "8686:8686"
  #     - "8001:8001"

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.14.0
  #   profiles:
  #     - observability
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  openldap:
    image: bitnamilegacy/openldap:2.6
    user: root
    restart: unless-stopped
    environment:
      LDAP_ADMIN_PASSWORD: "pass123"
    ports:
      - "389:1389"
    volumes:
      - ./ldap/entrypoint:/docker-entrypoint-initdb.d:ro
      - ./ldap/init.ldif:/ldifs/init.ldif:ro
      - ./ldap/custom.ldif:/schema/custom.ldif:ro
      - ./.volumes/openldap:/bitnami/openldap
