# This is an example config file for defguard
# To use it fill in actual values for your deployment below
# More info: https://defguard.gitbook.io/defguard/features/setting-up-your-instance/configuration

log_level = "info"
# Optional: path to defguard log file
# log_file = /var/log/defguard.log

# Optional: auth cookie lifetime (in seconds
# session_auth_lifetime = 86400

# JWT secret key for encrypting private cookies; must be at least 64 characters long
secret_key = "YOUR_SECRET_KEY"

# PostgreSQL server configuration
database_host = "localhost"
database_port = 5433
database_name = "defguard"
database_user = "defguard"
database_password = "YOUR_DATABASE_PASSWORD"

# port the API server will listen on
http_port = 8080
# port the gRPC server will listen on
grpc_port = 50051

# gRPC SSL configuration
# provide certificate and key to connect to gRPC server with HTTPS
# https://defguard.gitbook.io/defguard/features/setting-up-your-instance/docker-compose#grpc-ssl-setup
# Optional: path to cert file
# grpc_cert: proxy.crt
# Optional: path to key file
# grpc_key: proxy.key

# name of admin group
admin_groupname = "admin"

# name of user admin group
useradmin_groupname = "useradmin"

# name of VPN admin group
vpn_groupname = "vpn"

# password used when initializing first admin user
default_admin_password = "pass123"

# Optional: path to a private key file used for OAuth2/OpenID
# https://defguard.gitbook.io/defguard/features/setting-up-your-instance/docker-compose#openid-rsa-setup
# openid_signing_key =  /keys/openid.key

# Optional: relying party ID and relying party origin for WebAuthn.
# By default, it's generated by using a base domain of DEFGUARD_URL (for example https://defguard.example.com is converted to defguard.example.com)
# webauthn_rp_id = "defguard.example.com"

# external URL of your defguard instance Web UI & API server
url = "http://localhost:8000"

# external URL of your instance's gRPC server
grpc_url = "http://localhost:50055"

# disable periodic cleanup of old Wireguard stats
disable_stats_purge = false

# how often should the cleanup process be performed
stats_purge_frequency = "24h"

# age threshold for stats removal
stats_purge_threshold = "30d"

# external URL of the enrollment proxy server
enrollment_url = "http://localhost:8080"

# how long is the enrollment token valid for use
enrollment_token_timeout = "24h"

# how long in the enrollment session valid after a user uses the token to start the enrollment process
enrollment_session_timeout = "10m"

# how long is the password reset token valid for use
password_reset_token_timeout = "24h"

# how long in the password reset session valid after a user uses the token to start the password reset process
password_reset_session_timeout = "10m"

# Optional: set the domain for auth cookies. By default, it's the domain from `url` config above
# cookie_domain = "defguard.example.com"

# set cookies without the Secure flag; use only in dev environments when serving defguard without HTTPS
cookie_insecure = false

# Optional: proxy service gRPC endpoint URL
# proxy_url = "http://localhost:50051"

# Optional: path to TLS root certificate file, required if connecting to proxy gRPC service with HTTPS
# proxy_grpc_ca = "/ssl/defguard-ca.pem

# how long to wait to avoid sending gateway disconnect notifications too often
gateway_disconnection_notification_timeout = "10m"
