// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	messages: {
		/**
		 * E​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d​.
		 */
		error: string
		/**
		 * O​p​e​r​a​t​i​o​n​ ​s​u​c​c​e​e​d​e​d
		 */
		success: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​a​p​p​l​i​c​a​t​i​o​n​ ​v​e​r​s​i​o​n​.
		 */
		errorVersion: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​l​i​c​e​n​s​e​.
		 */
		errorLicense: string
		/**
		 * C​l​i​p​b​o​a​r​d​ ​i​s​ ​n​o​t​ ​a​c​c​e​s​s​i​b​l​e​.
		 */
		clipboardError: string
	}
	modals: {
		manageWebAuthNKeys: {
			/**
			 * S​e​c​u​r​i​t​y​ ​k​e​y​s
			 */
			title: string
			messages: {
				/**
				 * W​e​b​A​u​t​h​N​ ​k​e​y​ ​d​e​l​e​t​e​d​.
				 */
				deleted: string
			}
			/**
			 * 
		​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​S​e​c​u​r​i​t​y​ ​k​e​y​s​ ​c​a​n​ ​b​e​ ​u​s​e​d​ ​a​s​ ​y​o​u​r​ ​s​e​c​o​n​d​ ​f​a​c​t​o​r​ ​o​f​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​i​n​s​t​e​a​d​ ​o​f​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​.​ ​L​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​c​o​n​f​i​g​u​r​i​n​g​ ​a​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​s​e​c​u​r​i​t​y​ ​k​e​y​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
	
			 */
			infoMessage: string
			form: {
				messages: {
					/**
					 * S​e​c​u​r​i​t​y​ ​k​e​y​ ​a​d​d​e​d​.
					 */
					success: string
				}
				fields: {
					name: {
						/**
						 * N​e​w​ ​k​e​y​ ​n​a​m​e
						 */
						label: string
					}
				}
				controls: {
					/**
					 * A​d​d​ ​n​e​w​ ​K​e​y
					 */
					submit: string
				}
			}
		}
		recoveryCodes: {
			/**
			 * R​e​c​o​v​e​r​y​ ​c​o​d​e​s
			 */
			title: string
			/**
			 * I​ ​h​a​v​e​ ​s​a​v​e​d​ ​m​y​ ​c​o​d​e​s
			 */
			submit: string
			messages: {
				/**
				 * C​o​d​e​s​ ​c​o​p​i​e​d​.
				 */
				copied: string
			}
			/**
			 * 
		​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​T​r​e​a​t​ ​y​o​u​r​ ​r​e​c​o​v​e​r​y​ ​c​o​d​e​s​ ​w​i​t​h​ ​t​h​e​ ​s​a​m​e​ ​l​e​v​e​l​ ​o​f​ ​a​t​t​e​n​t​i​o​n​ ​a​s​ ​y​o​u​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​w​o​u​l​d​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​!​ ​W​e​ ​r​e​c​o​m​m​e​n​d​ ​s​a​v​i​n​g​ ​t​h​e​m​ ​w​i​t​h​ ​a​ ​p​a​s​s​w​o​r​d​ ​m​a​n​a​g​e​r​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​s​u​c​h​ ​a​s​ ​L​a​s​t​p​a​s​s​,​ ​b​i​t​w​a​r​d​e​n​ ​o​r​ ​K​e​e​p​e​r​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
	
			 */
			infoMessage: string
		}
		registerTOTP: {
			/**
			 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​A​p​p​ ​S​e​t​u​p
			 */
			title: string
			/**
			 * 
		​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​T​o​ ​s​e​t​u​p​ ​y​o​u​r​ ​M​F​A​,​ ​s​c​a​n​ ​t​h​i​s​ ​Q​R​ ​c​o​d​e​ ​w​i​t​h​ ​y​o​u​r​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​a​p​p​,​ ​t​h​e​n​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​e​n​t​e​r​ ​t​h​e​ ​c​o​d​e​ ​i​n​ ​t​h​e​ ​f​i​e​l​d​ ​b​e​l​o​w​:​
		​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
	
			 */
			infoMessage: string
			messages: {
				/**
				 * T​O​T​P​ ​p​a​t​h​ ​c​o​p​i​e​d​.
				 */
				totpCopied: string
				/**
				 * T​O​T​P​ ​E​n​a​b​l​e​d
				 */
				success: string
			}
			/**
			 * C​o​p​y​ ​T​O​T​P​ ​p​a​t​h
			 */
			copyPath: string
			form: {
				fields: {
					code: {
						/**
						 * A​u​t​h​e​n​t​i​c​a​t​o​r​ ​c​o​d​e
						 */
						label: string
						/**
						 * C​o​d​e​ ​i​s​ ​i​n​v​a​l​i​d
						 */
						error: string
					}
				}
				controls: {
					/**
					 * V​e​r​i​f​y​ ​c​o​d​e
					 */
					submit: string
				}
			}
		}
		editDevice: {
			/**
			 * E​d​i​t​ ​d​e​v​i​c​e
			 */
			title: string
			messages: {
				/**
				 * D​e​v​i​c​e​ ​u​p​d​a​t​e​d​.
				 */
				success: string
			}
			form: {
				fields: {
					name: {
						/**
						 * D​e​v​i​c​e​ ​N​a​m​e
						 */
						label: string
					}
					publicKey: {
						/**
						 * D​e​v​i​c​e​ ​P​u​b​l​i​c​ ​K​e​y​ ​(​W​i​r​e​g​u​a​r​d​)
						 */
						label: string
					}
				}
				controls: {
					/**
					 * E​d​i​t​ ​d​e​v​i​c​e
					 */
					submit: string
				}
			}
		}
		deleteDevice: {
			/**
			 * D​e​l​e​t​e​ ​d​e​v​i​c​e
			 */
			title: string
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​d​e​v​i​c​e​N​a​m​e​}​ ​d​e​v​i​c​e​ ​?
			 * @param {string} deviceName
			 */
			message: RequiredParams<'deviceName'>
			/**
			 * D​e​l​e​t​e​ ​d​e​v​i​c​e
			 */
			submit: string
			messages: {
				/**
				 * D​e​v​i​c​e​ ​d​e​l​e​t​e​d​.
				 */
				success: string
			}
		}
		addDevice: {
			messages: {
				/**
				 * D​e​v​i​c​e​ ​a​d​d​e​d​.
				 */
				success: string
			}
			web: {
				/**
				 * A​d​d​ ​d​e​v​i​c​e
				 */
				title: string
				steps: {
					config: {
						messages: {
							/**
							 * C​o​n​f​i​g​ ​c​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
							 */
							copyConfig: string
						}
						/**
						 * D​e​v​i​c​e​ ​N​a​m​e
						 */
						inputNameLabel: string
						/**
						 * 
					​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​P​l​e​a​s​e​ ​b​e​ ​a​d​v​i​s​e​d​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​t​o​ ​d​o​w​n​l​o​a​d​ ​t​h​e​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​n​o​w​,​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​s​i​n​c​e​ ​<​s​t​r​o​n​g​>​w​e​ ​d​o​ ​n​o​t​<​/​s​t​r​o​n​g​>​ ​s​t​o​r​e​ ​y​o​u​r​ ​p​r​i​v​a​t​e​ ​k​e​y​.​ ​A​f​t​e​r​ ​t​h​i​s​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​d​i​a​l​o​g​ ​i​s​ ​c​l​o​s​e​d​,​ ​y​o​u​ ​<​s​t​r​o​n​g​>​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​<​/​s​t​r​o​n​g​>​ ​t​o​ ​g​e​t​ ​y​o​u​r​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​f​u​l​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​(​w​i​t​h​ ​p​r​i​v​a​t​e​ ​k​e​y​s​,​ ​o​n​l​y​ ​b​l​a​n​k​ ​t​e​m​p​l​a​t​e​)​.​
					​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
				
						 */
						warningMessage: string
						/**
						 * U​s​e​ ​p​r​o​v​i​d​e​d​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​b​e​l​o​w​ ​b​y​ ​s​c​a​n​n​i​n​g​ ​Q​R​ ​C​o​d​e​ ​o​r​ ​i​m​p​o​r​t​i​n​g​ ​i​t​ ​a​s​ ​f​i​l​e​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​s​ ​W​i​r​e​G​u​a​r​d​ ​i​n​s​t​a​n​c​e​.
						 */
						qrInfo: string
						/**
						 * W​i​r​e​G​u​a​r​d​ ​C​o​n​f​i​g​ ​F​i​l​e
						 */
						qrLabel: string
						/**
						 * 
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​T​h​i​s​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​f​i​l​e​ ​c​a​n​ ​b​e​ ​s​c​a​n​n​e​d​,​ ​c​o​p​i​e​d​ ​o​r​ ​d​o​w​n​l​o​a​d​e​d​,​ ​b​u​t​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​u​s​e​d​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​s​t​r​o​n​g​>​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​t​h​a​t​ ​y​o​u​ ​a​r​e​ ​a​d​d​i​n​g​ ​n​o​w​.​<​/​s​t​r​o​n​g​>​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​>​R​e​a​d​ ​m​o​r​e​ ​i​n​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.​<​/​a​>​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>
						 */
						qrHelper: string
						/**
						 * W​i​r​e​G​u​a​r​d​ ​C​o​n​f​i​g
						 */
						qrCardTitle: string
					}
					setup: {
						/**
						 * 
					​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​Y​o​u​ ​n​e​e​d​ ​t​o​ ​c​o​n​f​i​g​u​r​e​ ​W​i​r​e​g​u​a​r​d​V​P​N​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​,​ ​p​l​e​a​s​e​ ​v​i​s​i​t​&​n​b​s​p​;​
					​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​"​>​d​o​c​u​m​e​n​t​a​t​i​o​n​<​/​a​>​ ​i​f​ ​y​o​u​ ​d​o​n​&​a​p​o​s​;​t​ ​k​n​o​w​ ​h​o​w​ ​t​o​ ​d​o​ ​i​t​.​
					​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
				
						 */
						infoMessage: string
						options: {
							/**
							 * G​e​n​e​r​a​t​e​ ​k​e​y​ ​p​a​i​r
							 */
							auto: string
							/**
							 * U​s​e​ ​m​y​ ​o​w​n​ ​p​u​b​l​i​c​ ​k​e​y
							 */
							manual: string
						}
						form: {
							/**
							 * G​e​n​e​r​a​t​e​ ​C​o​n​f​i​g
							 */
							submit: string
							fields: {
								name: {
									/**
									 * D​e​v​i​c​e​ ​N​a​m​e
									 */
									label: string
								}
								publicKey: {
									/**
									 * P​r​o​v​i​d​e​ ​Y​o​u​r​ ​P​u​b​l​i​c​ ​K​e​y
									 */
									label: string
								}
							}
						}
					}
				}
			}
			desktop: {
				/**
				 * A​d​d​ ​c​u​r​r​e​n​t​ ​d​e​v​i​c​e
				 */
				title: string
				form: {
					/**
					 * A​d​d​ ​t​h​i​s​ ​d​e​v​i​c​e
					 */
					submit: string
					fields: {
						name: {
							/**
							 * N​a​m​e
							 */
							label: string
						}
					}
				}
			}
		}
		addWallet: {
			/**
			 * A​d​d​ ​w​a​l​l​e​t
			 */
			title: string
			/**
			 * I​n​ ​o​r​d​e​r​ ​t​o​ ​a​d​d​ ​a​ ​E​T​H​ ​w​a​l​l​e​t​ ​y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​s​i​g​n​ ​m​e​s​s​a​g​e​.
			 */
			infoBox: string
			form: {
				fields: {
					name: {
						/**
						 * W​a​l​l​e​t​ ​n​a​m​e
						 */
						placeholder: string
						/**
						 * N​a​m​e
						 */
						label: string
					}
					address: {
						/**
						 * W​a​l​l​e​t​ ​a​d​d​r​e​s​s
						 */
						placeholder: string
						/**
						 * A​d​d​r​e​s​s
						 */
						label: string
					}
				}
				controls: {
					/**
					 * A​d​d​ ​w​a​l​l​e​t
					 */
					submit: string
				}
			}
		}
		keyDetails: {
			/**
			 * Y​u​b​i​K​e​y​ ​d​e​t​a​i​l​s
			 */
			title: string
			/**
			 * D​o​w​n​l​o​a​d​ ​a​l​l​ ​k​e​y​s
			 */
			downloadAll: string
		}
		deleteUser: {
			/**
			 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
			 */
			title: string
			controls: {
				/**
				 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
				 */
				submit: string
			}
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​u​s​e​r​n​a​m​e​}​ ​a​c​c​o​u​n​t​ ​p​e​r​m​a​n​e​n​t​l​y​ ​?
			 * @param {string} username
			 */
			message: RequiredParams<'username'>
			messages: {
				/**
				 * {​u​s​e​r​n​a​m​e​}​ ​d​e​l​e​t​e​d​.
				 * @param {string} username
				 */
				success: RequiredParams<'username'>
			}
		}
		changeUserPassword: {
			messages: {
				/**
				 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​.
				 */
				success: string
			}
			/**
			 * C​h​a​n​g​e​ ​u​s​e​r​ ​p​a​s​s​w​o​r​d
			 */
			title: string
			form: {
				controls: {
					/**
					 * S​a​v​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d
					 */
					submit: string
				}
				fields: {
					newPassword: {
						/**
						 * N​e​w​ ​p​a​s​s​w​o​r​d
						 */
						label: string
					}
					confirmPassword: {
						/**
						 * R​e​p​e​a​t​ ​p​a​s​s​w​o​r​d
						 */
						label: string
					}
				}
			}
		}
		provisionKeys: {
			/**
			 * Y​u​b​i​k​e​y​ ​p​r​o​v​i​s​i​o​n​i​n​g​:
			 */
			title: string
			/**
			 * T​h​e​ ​s​e​l​e​c​t​e​d​ ​p​r​o​v​i​s​i​o​n​e​r​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​<​b​>​c​l​e​a​n​<​/​b​>​ ​Y​u​b​i​K​e​y​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​p​l​u​g​g​e​d​ ​i​n​ ​b​e​ ​p​r​o​v​i​s​i​o​n​e​d​.​ ​T​o​ ​c​l​e​a​n​ ​a​ ​u​s​e​d​ ​Y​u​b​i​K​e​y​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​>​g​p​g​-​c​a​r​d​ ​f​a​c​t​o​r​y​ ​r​e​s​e​t​<​/​b​>​ ​b​e​f​o​r​e​ ​p​r​o​v​i​s​i​o​n​i​n​g​.
			 */
			infoBox: string
			/**
			 * S​e​l​e​c​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​p​r​o​v​i​s​i​o​n​e​r​s​ ​t​o​ ​p​r​o​v​i​s​i​o​n​ ​a​ ​Y​u​b​i​K​e​y​:
			 */
			selectionLabel: string
			noData: {
				/**
				 * N​o​ ​w​o​r​k​e​r​s​ ​f​o​u​n​d​,​ ​w​a​i​t​i​n​g​.​.​.
				 */
				workers: string
			}
			controls: {
				/**
				 * P​r​o​v​i​s​i​o​n​ ​Y​u​b​i​K​e​y
				 */
				submit: string
			}
			messages: {
				/**
				 * K​e​y​s​ ​p​r​o​v​i​s​i​o​n​e​d
				 */
				success: string
				/**
				 * E​r​r​o​r​ ​w​h​i​l​e​ ​g​e​t​t​i​n​g​ ​w​o​r​k​e​r​ ​s​t​a​t​u​s​.
				 */
				errorStatus: string
			}
		}
		addUser: {
			/**
			 * A​d​d​ ​n​e​w​ ​u​s​e​r
			 */
			title: string
			form: {
				/**
				 * A​d​d​ ​u​s​e​r
				 */
				submit: string
				fields: {
					username: {
						/**
						 * l​o​g​i​n
						 */
						placeholder: string
						/**
						 * L​o​g​i​n
						 */
						label: string
					}
					password: {
						/**
						 * P​a​s​s​w​o​r​d
						 */
						placeholder: string
						/**
						 * P​a​s​s​w​o​r​d
						 */
						label: string
					}
					email: {
						/**
						 * U​s​e​r​ ​e​-​m​a​i​l
						 */
						placeholder: string
						/**
						 * U​s​e​r​ ​e​-​m​a​i​l
						 */
						label: string
					}
					firstName: {
						/**
						 * F​i​r​s​t​ ​n​a​m​e
						 */
						placeholder: string
						/**
						 * F​i​r​s​t​ ​n​a​m​e
						 */
						label: string
					}
					lastName: {
						/**
						 * L​a​s​t​ ​n​a​m​e
						 */
						placeholder: string
						/**
						 * L​a​s​t​ ​n​a​m​e
						 */
						label: string
					}
					phone: {
						/**
						 * P​h​o​n​e
						 */
						placeholder: string
						/**
						 * P​h​o​n​e
						 */
						label: string
					}
				}
			}
		}
	}
	userPage: {
		title: {
			/**
			 * U​s​e​r​ ​P​r​o​f​i​l​e
			 */
			view: string
			/**
			 * E​d​i​t​ ​U​s​e​r​ ​P​r​o​f​i​l​e
			 */
			edit: string
		}
		messages: {
			/**
			 * U​s​e​r​ ​u​p​d​a​t​e​d​.
			 */
			editSuccess: string
		}
		userDetails: {
			/**
			 * P​r​o​f​i​l​e​ ​D​e​t​a​i​l​s
			 */
			header: string
			messages: {
				/**
				 * A​p​p​ ​a​n​d​ ​a​l​l​ ​t​o​k​e​n​s​ ​d​e​l​e​t​e​d​.
				 */
				deleteApp: string
			}
			fields: {
				username: {
					/**
					 * U​s​e​r​n​a​m​e
					 */
					label: string
				}
				firstName: {
					/**
					 * F​i​r​s​t​ ​n​a​m​e
					 */
					label: string
				}
				lastName: {
					/**
					 * L​a​s​t​ ​n​a​m​e
					 */
					label: string
				}
				phone: {
					/**
					 * P​h​o​n​e​ ​n​u​m​b​e​r
					 */
					label: string
				}
				email: {
					/**
					 * E​-​m​a​i​l
					 */
					label: string
				}
				groups: {
					/**
					 * U​s​e​r​ ​g​r​o​u​p​s
					 */
					label: string
					/**
					 * N​o​ ​g​r​o​u​p​s
					 */
					noData: string
				}
				apps: {
					/**
					 * A​u​t​h​o​r​i​z​e​d​ ​a​p​p​s
					 */
					label: string
					/**
					 * N​o​ ​a​u​t​h​o​r​i​z​e​d​ ​a​p​p​s
					 */
					noData: string
				}
			}
		}
		userAuthInfo: {
			/**
			 * P​a​s​s​w​o​r​d​ ​a​n​d​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n
			 */
			header: string
			password: {
				/**
				 * P​a​s​s​w​o​r​d​ ​s​e​t​t​i​n​g​s
				 */
				header: string
				/**
				 * C​h​a​n​g​e​ ​p​a​s​s​w​o​r​d
				 */
				changePassword: string
			}
			recovery: {
				/**
				 * R​e​c​o​v​e​r​y​ ​o​p​t​i​o​n​s
				 */
				header: string
				codes: {
					/**
					 * R​e​c​o​v​e​r​y​ ​C​o​d​e​s
					 */
					label: string
					/**
					 * V​i​e​w​e​d
					 */
					viewed: string
				}
			}
			mfa: {
				/**
				 * T​w​o​-​f​a​c​t​o​r​ ​m​e​t​h​o​d​s
				 */
				header: string
				edit: {
					/**
					 * D​i​s​a​b​l​e​ ​M​F​A
					 */
					disable: string
				}
				messages: {
					/**
					 * M​F​A​ ​d​i​s​a​b​l​e​d​.
					 */
					mfaDisabled: string
					/**
					 * O​n​e​ ​t​i​m​e​ ​p​a​s​s​w​o​r​d​ ​d​i​s​a​b​l​e​d​.
					 */
					OTPDisabled: string
					/**
					 * M​F​A​ ​m​e​t​h​o​d​ ​c​h​a​n​g​e​d
					 */
					changeMFAMethod: string
				}
				securityKey: {
					/**
					 * s​e​c​u​r​i​t​y​ ​k​e​y
					 */
					singular: string
					/**
					 * s​e​c​u​r​i​t​y​ ​k​e​y​s
					 */
					plural: string
				}
				/**
				 * d​e​f​a​u​l​t
				 */
				'default': string
				/**
				 * E​n​a​b​l​e​d
				 */
				enabled: string
				/**
				 * D​i​s​a​b​l​e​d
				 */
				disabled: string
				wallet: {
					/**
					 * W​a​l​l​e​t
					 */
					singular: string
					/**
					 * W​a​l​l​e​t​s
					 */
					plural: string
				}
				labels: {
					/**
					 * T​i​m​e​ ​b​a​s​e​d​ ​o​n​e​ ​t​i​m​e​ ​p​a​s​s​w​o​r​d​s
					 */
					totp: string
					/**
					 * S​e​c​u​r​i​t​y​ ​k​e​y​s
					 */
					webauth: string
					/**
					 * W​a​l​l​e​t​s
					 */
					wallets: string
				}
				editMode: {
					/**
					 * E​n​a​b​l​e
					 */
					enable: string
					/**
					 * D​i​s​a​b​l​e
					 */
					disable: string
					/**
					 * M​a​k​e​ ​d​e​f​a​u​l​t
					 */
					makeDefault: string
					webauth: {
						/**
						 * M​a​n​a​g​e​ ​s​e​c​u​r​i​t​y​ ​k​e​y​s
						 */
						manage: string
					}
				}
			}
		}
		controls: {
			/**
			 * E​d​i​t​ ​p​r​o​f​i​l​e
			 */
			editButton: string
			/**
			 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
			 */
			deleteAccount: string
		}
		devices: {
			/**
			 * U​s​e​r​ ​d​e​v​i​c​e​s
			 */
			header: string
			addDevice: {
				/**
				 * A​d​d​ ​n​e​w​ ​d​e​v​i​c​e
				 */
				web: string
				/**
				 * A​d​d​ ​t​h​i​s​ ​d​e​v​i​c​e
				 */
				desktop: string
			}
			card: {
				labels: {
					/**
					 * L​a​s​t​ ​l​o​c​a​t​i​o​n
					 */
					location: string
					/**
					 * L​a​s​t​ ​I​P​ ​a​d​d​r​e​s​s
					 */
					lastIpAddress: string
					/**
					 * D​a​t​e​ ​a​d​d​e​d
					 */
					date: string
				}
				edit: {
					/**
					 * E​d​i​t​ ​d​e​v​i​c​e
					 */
					edit: string
					/**
					 * D​o​w​n​l​o​a​d​ ​c​o​n​f​i​g
					 */
					download: string
					/**
					 * D​e​l​e​t​e​ ​d​e​v​i​c​e
					 */
					'delete': string
				}
			}
		}
		wallets: {
			messages: {
				duplicate: {
					/**
					 * C​o​n​n​e​c​t​e​d​ ​w​a​l​l​e​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d
					 */
					primary: string
					/**
					 * P​l​e​a​s​e​ ​c​o​n​n​e​c​t​ ​u​n​u​s​e​d​ ​w​a​l​l​e​t​.
					 */
					sub: string
				}
			}
			/**
			 * U​s​e​r​ ​w​a​l​l​e​t​s
			 */
			header: string
			/**
			 * A​d​d​ ​n​e​w​ ​w​a​l​l​e​t
			 */
			addWallet: string
			card: {
				/**
				 * A​d​d​r​e​s​s
				 */
				address: string
				/**
				 * M​F​A
				 */
				mfaBadge: string
				edit: {
					/**
					 * E​n​a​b​l​e​ ​M​F​A
					 */
					enableMFA: string
					/**
					 * D​i​s​a​b​l​e​ ​M​F​A
					 */
					disableMFA: string
					/**
					 * D​e​l​e​t​e
					 */
					'delete': string
				}
				messages: {
					/**
					 * W​a​l​l​e​t​ ​d​e​l​e​t​e​d
					 */
					deleteSuccess: string
					/**
					 * W​a​l​l​e​t​ ​M​F​A​ ​e​n​a​b​l​e​d
					 */
					enableMFA: string
					/**
					 * W​a​l​l​e​t​ ​M​F​A​ ​d​i​s​a​b​l​e​d
					 */
					disableMFA: string
				}
			}
		}
		yubiKey: {
			/**
			 * U​s​e​r​ ​Y​u​b​i​K​e​y
			 */
			header: string
			/**
			 * P​r​o​v​i​s​i​o​n​ ​a​ ​Y​u​b​i​K​e​y
			 */
			provision: string
			keys: {
				/**
				 * P​G​P​ ​k​e​y
				 */
				pgp: string
				/**
				 * S​S​H​ ​k​e​y
				 */
				ssh: string
			}
			noLicense: {
				/**
				 * Y​u​b​i​K​e​y​ ​m​o​d​u​l​e
				 */
				moduleName: string
				/**
				 * T​h​i​s​ ​i​s​ ​e​n​t​e​r​p​r​i​s​e​ ​m​o​d​u​l​e​ ​f​o​r​ ​Y​u​b​i​K​e​y
				 */
				line1: string
				/**
				 * m​a​n​a​g​e​m​e​n​t​ ​a​n​d​ ​p​r​o​v​i​s​i​o​n​i​n​g​.
				 */
				line2: string
			}
		}
	}
	usersOverview: {
		/**
		 * U​s​e​r​s
		 */
		pageTitle: string
		search: {
			/**
			 * F​i​n​d​ ​u​s​e​r​s
			 */
			placeholder: string
		}
		filterLabels: {
			/**
			 * A​l​l​ ​u​s​e​r​s
			 */
			all: string
			/**
			 * A​d​m​i​n​s​ ​o​n​l​y
			 */
			admin: string
			/**
			 * U​s​e​r​s​ ​o​n​l​y
			 */
			users: string
		}
		/**
		 * A​l​l​ ​u​s​e​r​s
		 */
		usersCount: string
		/**
		 * A​d​d​ ​n​e​w
		 */
		addNewUser: string
		list: {
			headers: {
				/**
				 * U​s​e​r​ ​n​a​m​e
				 */
				name: string
				/**
				 * L​o​g​i​n
				 */
				username: string
				/**
				 * P​h​o​n​e
				 */
				phone: string
				/**
				 * A​c​t​i​o​n​s
				 */
				actions: string
			}
			editButton: {
				/**
				 * C​h​a​n​g​e​ ​p​a​s​s​w​o​r​d
				 */
				changePassword: string
				/**
				 * E​d​i​t​ ​a​c​c​o​u​n​t
				 */
				edit: string
				/**
				 * P​r​o​v​i​s​i​o​n​ ​Y​u​b​i​K​e​y
				 */
				provision: string
				/**
				 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
				 */
				'delete': string
			}
		}
	}
	navigation: {
		bar: {
			/**
			 * O​v​e​r​v​i​e​w
			 */
			overview: string
			/**
			 * U​s​e​r​s
			 */
			users: string
			/**
			 * P​r​o​v​i​s​i​o​n​e​r​s
			 */
			provisioners: string
			/**
			 * W​e​b​h​o​o​k​s
			 */
			webhooks: string
			/**
			 * O​p​e​n​I​D​ ​A​p​p​s
			 */
			openId: string
			/**
			 * M​y​ ​P​r​o​f​i​l​e
			 */
			myProfile: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * L​o​g​ ​o​u​t
			 */
			logOut: string
		}
		mobileTitles: {
			/**
			 * U​s​e​r​s
			 */
			users: string
			/**
			 * D​e​f​g​u​a​r​d​ ​G​l​o​b​a​l​ ​S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * U​s​e​r​ ​P​r​o​f​i​l​e
			 */
			user: string
			/**
			 * P​r​o​v​i​s​i​o​n​e​r​s
			 */
			provisioners: string
			/**
			 * W​e​b​h​o​o​k​s
			 */
			webhooks: string
			/**
			 * O​p​e​n​I​d​ ​A​p​p​s
			 */
			openId: string
			/**
			 * N​e​t​w​o​r​k​ ​O​v​e​r​v​i​e​w
			 */
			overview: string
			/**
			 * N​e​t​w​o​r​k​ ​S​e​t​t​i​n​g​s
			 */
			networkSettings: string
		}
		/**
		 * C​o​p​y​r​i​g​h​t​ ​©​ ​2​0​2​3
		 */
		copyright: string
		/**
		 * A​p​p​l​i​c​a​t​i​o​n​ ​v​e​r​s​i​o​n​:​ ​{​v​e​r​s​i​o​n​}
		 * @param {string} version
		 */
		version: RequiredParams<'version'>
	}
	form: {
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * S​a​v​e​ ​c​h​a​n​g​e​s
		 */
		saveChanges: string
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		placeholders: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
		}
		error: {
			/**
			 * U​s​e​r​n​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
			 */
			usernameTaken: string
			/**
			 * K​e​y​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			invalidKey: string
			/**
			 * F​i​e​l​d​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			invalid: string
			/**
			 * F​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			required: string
			/**
			 * M​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​e​x​c​e​e​d​e​d​.
			 */
			maximumLength: string
			/**
			 * M​i​n​i​m​u​m​ ​l​e​n​g​t​h​ ​n​o​t​ ​r​e​a​c​h​e​d​.
			 */
			minimumLength: string
			/**
			 * N​o​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​.
			 */
			noSpecialChars: string
			/**
			 * O​n​e​ ​d​i​g​i​t​ ​r​e​q​u​i​r​e​d​.
			 */
			oneDigit: string
			/**
			 * S​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneSpecial: string
			/**
			 * O​n​e​ ​u​p​p​e​r​c​a​s​e​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneUppercase: string
			/**
			 * O​n​e​ ​l​o​w​e​r​c​a​s​e​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneLowercase: string
		}
	}
	components: {
		noLicenseBox: {
			footer: {
				/**
				 * G​e​t​ ​a​n​ ​e​n​t​e​r​p​r​i​s​e​ ​l​i​c​e​n​s​e
				 */
				get: string
				/**
				 * b​y​ ​c​o​n​t​a​c​t​i​n​g​:
				 */
				contact: string
			}
		}
	}
	settingsPage: {
		/**
		 * G​l​o​b​a​l​ ​S​e​t​t​i​n​g​s
		 */
		title: string
		messages: {
			/**
			 * E​r​r​o​r​ ​o​c​c​u​r​e​d​!​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​a​d​m​i​n​i​s​t​r​a​t​o​r
			 */
			error: string
			/**
			 * S​e​t​t​i​n​g​s​ ​u​p​d​a​t​e​d
			 */
			editSuccess: string
		}
		modulesVisibility: {
			/**
			 * M​o​d​u​l​e​s​ ​V​i​s​i​b​i​l​i​t​y
			 */
			header: string
			/**
			 * <​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​I​f​ ​y​o​u​r​ ​n​o​t​ ​u​s​i​n​g​ ​s​o​m​e​ ​m​o​d​u​l​e​s​ ​y​o​u​ ​c​a​n​ ​d​i​s​a​b​l​e​ ​t​h​e​i​r​ ​v​i​s​i​b​i​l​i​t​y​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​d​e​f​g​u​a​r​d​.​g​i​t​b​o​o​k​.​i​o​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​R​e​a​d​ ​m​o​r​e​ ​i​n​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​a​>
			 */
			helper: string
			fields: {
				wireguard_enabled: {
					/**
					 * W​i​r​e​g​u​a​r​d​ ​V​P​N
					 */
					label: string
				}
				webhooks_enabled: {
					/**
					 * W​e​b​h​o​o​k​s
					 */
					label: string
				}
				web3_enabled: {
					/**
					 * W​e​b​3
					 */
					label: string
				}
				worker_enabled: {
					/**
					 * Y​u​b​i​B​r​i​d​g​e
					 */
					label: string
				}
				openid_enabled: {
					/**
					 * O​p​e​n​I​D​ ​c​o​n​n​e​c​t
					 */
					label: string
				}
				oauth_enabled: {
					/**
					 * O​A​u​t​h​2
					 */
					label: string
				}
			}
		}
		defaultNetworkSelect: {
			/**
			 * D​e​f​a​u​l​t​ ​n​e​t​w​o​r​k​ ​v​i​e​w
			 */
			header: string
			/**
			 * <​p​>​H​e​r​e​ ​y​o​u​ ​c​a​n​ ​c​h​a​n​g​e​ ​y​o​u​r​ ​d​e​f​a​u​l​t​ ​n​e​t​w​o​r​k​ ​v​i​e​w​.​<​/​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​d​e​f​g​u​a​r​d​.​g​i​t​b​o​o​k​.​i​o​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​R​e​a​d​ ​m​o​r​e​ ​i​n​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​a​>
			 */
			helper: string
		}
		web3Settings: {
			/**
			 * W​e​b​3​ ​/​ ​W​a​l​l​e​t​ ​c​o​n​n​e​c​t
			 */
			header: string
			fields: {
				signMessage: {
					/**
					 * D​e​f​a​u​l​t​ ​s​i​g​n​ ​m​e​s​s​a​g​e​ ​t​e​m​p​l​a​t​e
					 */
					label: string
				}
			}
			controls: {
				/**
				 * S​a​v​e​ ​c​h​a​n​g​e​s
				 */
				save: string
			}
		}
		instanceBranding: {
			/**
			 * I​n​s​t​a​n​c​e​ ​B​r​a​n​d​i​n​g
			 */
			header: string
			form: {
				/**
				 * N​a​m​e​ ​&​ ​L​o​g​o​:
				 */
				title: string
				fields: {
					instanceName: {
						/**
						 * I​n​s​t​a​n​c​e​ ​n​a​m​e
						 */
						label: string
						/**
						 * D​e​f​g​u​a​r​d
						 */
						placeholder: string
					}
					mainLogoUrl: {
						/**
						 * L​o​g​i​n​ ​l​o​g​o​ ​u​r​l
						 */
						label: string
						/**
						 * D​e​f​a​u​l​t​ ​i​m​a​g​e
						 */
						placeholder: string
					}
					navLogoUrl: {
						/**
						 * N​a​v​i​g​a​t​i​o​n​ ​L​o​g​o​ ​u​r​l
						 */
						label: string
						/**
						 * D​e​f​a​u​l​t​ ​i​m​a​g​e
						 */
						placeholder: string
					}
				}
				error: {
					/**
					 * F​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
					 */
					required: string
					/**
					 * M​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​e​x​c​e​e​d​e​d
					 */
					maximumLength: string
					/**
					 * S​h​o​u​l​d​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
					 */
					minimumLength: string
				}
				controls: {
					/**
					 * R​e​s​t​o​r​e​ ​d​e​f​a​u​l​t
					 */
					restoreDefault: string
					/**
					 * S​a​v​e​ ​c​h​a​n​g​e​s
					 */
					submit: string
				}
			}
			/**
			 * 
		​	​	​	​ ​ ​ ​ ​ ​ ​<​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​H​e​r​e​ ​y​o​u​ ​c​a​n​ ​a​d​d​ ​u​r​l​ ​o​f​ ​y​o​u​r​ ​l​o​g​o​ ​a​n​d​ ​n​a​m​e​ ​f​o​r​ ​y​o​u​r​ ​d​e​f​g​u​a​r​d​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​i​n​s​t​a​n​c​e​ ​i​t​ ​w​i​l​l​ ​b​e​ ​d​i​s​p​l​a​y​e​d​ ​i​n​s​t​e​a​d​ ​o​f​ ​d​e​f​g​u​a​r​d​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​d​e​f​g​u​a​r​d​.​g​i​t​b​o​o​k​.​i​o​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​>​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​R​e​a​d​ ​m​o​r​e​ ​i​n​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​a​>​
		​	​	​
			 */
			helper: string
		}
		licenseCard: {
			/**
			 * L​i​c​e​n​s​e​ ​&​ ​S​u​p​p​o​r​t​ ​I​n​f​o​r​m​a​t​i​o​n
			 */
			header: string
			licenseCardTitles: {
				/**
				 * C​o​m​m​u​n​i​t​y
				 */
				community: string
				/**
				 * E​n​t​e​r​p​r​i​s​e
				 */
				enterprise: string
				/**
				 * l​i​c​e​n​s​e
				 */
				license: string
			}
			body: {
				/**
				 * 
			​	​	​	​	​<​p​>​ ​T​h​a​n​k​ ​y​o​u​ ​f​o​r​ ​p​u​r​c​h​a​s​i​n​g​ ​e​n​t​e​r​p​r​i​s​e​ ​l​i​c​e​n​s​e​!​<​/​p​>​
			​	​	​	​	​<​b​r​ ​/​>​
			​	​	​	​	​<​p​>​T​h​i​s​ ​i​n​c​l​u​d​e​s​ ​f​o​l​l​o​w​i​n​g​ ​m​o​d​u​l​e​s​:​<​/​p​>
				 */
				enterprise: string
				/**
				 * 
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​Y​o​u​ ​h​a​v​e​ ​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​l​i​c​e​n​s​e​.​ ​I​f​ ​y​o​u​ ​w​i​s​h​ ​t​o​ ​g​e​t​ ​E​n​t​e​r​p​r​i​s​e​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​l​i​c​e​n​s​e​ ​f​o​r​ ​f​u​l​l​ ​f​e​a​t​u​r​e​s​ ​s​e​t​ ​a​n​d​ ​s​u​p​p​o​r​t​,​ ​p​l​e​a​s​e​ ​v​i​s​i​t​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​d​e​f​g​u​a​r​d​.​n​e​t​"​>​h​t​t​p​s​:​/​/​d​e​f​g​u​a​r​d​.​n​e​t​<​/​a​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​p​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​r​ ​/​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​p​>​E​n​t​e​r​p​r​i​s​e​ ​l​i​c​e​n​s​e​ ​i​n​c​l​u​d​e​s​:​<​/​p​>​
			​	​	​	​
				 */
				community: string
				/**
				 * r​e​a​d​ ​l​i​c​e​n​s​e​ ​a​g​r​e​e​m​e​n​t
				 */
				agreement: string
				/**
				 * 
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​u​l​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​Y​u​b​i​B​r​i​d​g​e​<​/​l​i​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​O​p​e​n​I​D​<​/​l​i​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​l​i​>​O​p​e​n​L​D​A​P​<​/​l​i​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​/​u​l​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​r​ ​/​>
				 */
				modules: string
			}
			footer: {
				/**
				 * l​i​c​e​n​s​e​d​ ​t​o​:​ ​{​c​o​m​p​a​n​y​}
				 * @param {string} company
				 */
				company: RequiredParams<'company'>
				/**
				 * e​x​p​i​r​a​t​i​o​n​ ​d​a​t​e​:​ ​{​e​x​p​i​r​a​t​i​o​n​}
				 * @param {string} expiration
				 */
				expiration: RequiredParams<'expiration'>
			}
		}
		supportCard: {
			/**
			 * S​u​p​p​o​r​t
			 */
			title: string
			body: {
				/**
				 * 
			​	​	​	​<​p​>​F​o​r​ ​E​n​t​e​r​p​r​i​s​e​ ​s​u​p​p​o​r​t​<​/​p​>​
			​ ​ ​ ​ ​ ​ ​<​p​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​:​ ​
			​ ​ ​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​m​a​i​l​t​o​:​s​u​p​p​o​r​t​@​d​e​f​g​u​a​r​d​.​n​e​t​"​>​s​u​p​p​o​r​t​@​d​e​f​g​u​a​r​d​.​n​e​t​<​/​a​>​
			​ ​ ​ ​ ​ ​ ​<​/​p​>​
			​	​	​	​<​b​r​/​>​
			​ ​ ​ ​ ​ ​ ​<​p​>​Y​o​u​ ​c​a​n​ ​a​l​s​o​ ​v​i​s​i​t​ ​o​u​r​ ​C​o​m​m​u​n​i​t​y​ ​s​u​p​p​o​r​t​:​<​/​p​>​
			​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​D​e​f​g​u​a​r​d​/​d​e​f​g​u​a​r​d​"​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​D​e​f​g​u​a​r​d​/​d​e​f​g​u​a​r​d​
			​ ​ ​ ​ ​ ​ ​<​/​a​>​
			​	​	​
				 */
				enterprise: string
				/**
				 * <​p​>​F​o​r​ ​C​o​m​m​u​n​i​t​y​ ​s​u​p​p​o​r​t​ ​P​l​e​a​s​e​ ​v​i​s​i​t​:​<​/​p​>​
			​ ​ ​ ​ ​ ​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​D​e​f​g​u​a​r​d​/​d​e​f​g​u​a​r​d​"​>​
			​ ​ ​ ​ ​ ​ ​ ​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​D​e​f​g​u​a​r​d​/​d​e​f​g​u​a​r​d​
			​ ​ ​ ​ ​ ​ ​<​/​a​>​
			​	​	​
				 */
				community: string
			}
		}
	}
}

export type TranslationFunctions = {
	messages: {
		/**
		 * Error has occurred.
		 */
		error: () => LocalizedString
		/**
		 * Operation succeeded
		 */
		success: () => LocalizedString
		/**
		 * Failed to get application version.
		 */
		errorVersion: () => LocalizedString
		/**
		 * Failed to get license.
		 */
		errorLicense: () => LocalizedString
		/**
		 * Clipboard is not accessible.
		 */
		clipboardError: () => LocalizedString
	}
	modals: {
		manageWebAuthNKeys: {
			/**
			 * Security keys
			 */
			title: () => LocalizedString
			messages: {
				/**
				 * WebAuthN key deleted.
				 */
				deleted: () => LocalizedString
			}
			/**
			 * 
		        <p>
		          Security keys can be used as your second factor of authentication
		          instead of a verification code. Learn more about configuring a
		          security key.
		        </p>
	
			 */
			infoMessage: () => LocalizedString
			form: {
				messages: {
					/**
					 * Security key added.
					 */
					success: () => LocalizedString
				}
				fields: {
					name: {
						/**
						 * New key name
						 */
						label: () => LocalizedString
					}
				}
				controls: {
					/**
					 * Add new Key
					 */
					submit: () => LocalizedString
				}
			}
		}
		recoveryCodes: {
			/**
			 * Recovery codes
			 */
			title: () => LocalizedString
			/**
			 * I have saved my codes
			 */
			submit: () => LocalizedString
			messages: {
				/**
				 * Codes copied.
				 */
				copied: () => LocalizedString
			}
			/**
			 * 
		        <p>
		          Treat your recovery codes with the same level of attention as you
		          would your password! We recommend saving them with a password manager
		          such as Lastpass, bitwarden or Keeper.
		        </p>
	
			 */
			infoMessage: () => LocalizedString
		}
		registerTOTP: {
			/**
			 * Authenticator App Setup
			 */
			title: () => LocalizedString
			/**
			 * 
		        <p>
		          To setup your MFA, scan this QR code with your authenticator app, then
		          enter the code in the field below:
		        </p>
	
			 */
			infoMessage: () => LocalizedString
			messages: {
				/**
				 * TOTP path copied.
				 */
				totpCopied: () => LocalizedString
				/**
				 * TOTP Enabled
				 */
				success: () => LocalizedString
			}
			/**
			 * Copy TOTP path
			 */
			copyPath: () => LocalizedString
			form: {
				fields: {
					code: {
						/**
						 * Authenticator code
						 */
						label: () => LocalizedString
						/**
						 * Code is invalid
						 */
						error: () => LocalizedString
					}
				}
				controls: {
					/**
					 * Verify code
					 */
					submit: () => LocalizedString
				}
			}
		}
		editDevice: {
			/**
			 * Edit device
			 */
			title: () => LocalizedString
			messages: {
				/**
				 * Device updated.
				 */
				success: () => LocalizedString
			}
			form: {
				fields: {
					name: {
						/**
						 * Device Name
						 */
						label: () => LocalizedString
					}
					publicKey: {
						/**
						 * Device Public Key (Wireguard)
						 */
						label: () => LocalizedString
					}
				}
				controls: {
					/**
					 * Edit device
					 */
					submit: () => LocalizedString
				}
			}
		}
		deleteDevice: {
			/**
			 * Delete device
			 */
			title: () => LocalizedString
			/**
			 * Do you want to delete {deviceName} device ?
			 */
			message: (arg: { deviceName: string }) => LocalizedString
			/**
			 * Delete device
			 */
			submit: () => LocalizedString
			messages: {
				/**
				 * Device deleted.
				 */
				success: () => LocalizedString
			}
		}
		addDevice: {
			messages: {
				/**
				 * Device added.
				 */
				success: () => LocalizedString
			}
			web: {
				/**
				 * Add device
				 */
				title: () => LocalizedString
				steps: {
					config: {
						messages: {
							/**
							 * Config copied to clipboard
							 */
							copyConfig: () => LocalizedString
						}
						/**
						 * Device Name
						 */
						inputNameLabel: () => LocalizedString
						/**
						 * 
					        <p>
					          Please be advised that you have to download the configuration now,
					          since <strong>we do not</strong> store your private key. After this
					          dialog is closed, you <strong>will not be able</strong> to get your
					          full configuration file (with private keys, only blank template).
					        </p>
				
						 */
						warningMessage: () => LocalizedString
						/**
						 * Use provided configuration file below by scanning QR Code or importing it as file on your devices WireGuard instance.
						 */
						qrInfo: () => LocalizedString
						/**
						 * WireGuard Config File
						 */
						qrLabel: () => LocalizedString
						/**
						 * 
					          <p>
					            This configuration file can be scanned, copied or downloaded, but
					            needs to be used
					            <strong>on your device that you are adding now.</strong>
					            <a>Read more in documentation.</a>
					          </p>
						 */
						qrHelper: () => LocalizedString
						/**
						 * WireGuard Config
						 */
						qrCardTitle: () => LocalizedString
					}
					setup: {
						/**
						 * 
					        <p>
					          You need to configure WireguardVPN on your device, please visit&nbsp;
					          <a href="">documentation</a> if you don&apos;t know how to do it.
					        </p>
				
						 */
						infoMessage: () => LocalizedString
						options: {
							/**
							 * Generate key pair
							 */
							auto: () => LocalizedString
							/**
							 * Use my own public key
							 */
							manual: () => LocalizedString
						}
						form: {
							/**
							 * Generate Config
							 */
							submit: () => LocalizedString
							fields: {
								name: {
									/**
									 * Device Name
									 */
									label: () => LocalizedString
								}
								publicKey: {
									/**
									 * Provide Your Public Key
									 */
									label: () => LocalizedString
								}
							}
						}
					}
				}
			}
			desktop: {
				/**
				 * Add current device
				 */
				title: () => LocalizedString
				form: {
					/**
					 * Add this device
					 */
					submit: () => LocalizedString
					fields: {
						name: {
							/**
							 * Name
							 */
							label: () => LocalizedString
						}
					}
				}
			}
		}
		addWallet: {
			/**
			 * Add wallet
			 */
			title: () => LocalizedString
			/**
			 * In order to add a ETH wallet you will need to sign message.
			 */
			infoBox: () => LocalizedString
			form: {
				fields: {
					name: {
						/**
						 * Wallet name
						 */
						placeholder: () => LocalizedString
						/**
						 * Name
						 */
						label: () => LocalizedString
					}
					address: {
						/**
						 * Wallet address
						 */
						placeholder: () => LocalizedString
						/**
						 * Address
						 */
						label: () => LocalizedString
					}
				}
				controls: {
					/**
					 * Add wallet
					 */
					submit: () => LocalizedString
				}
			}
		}
		keyDetails: {
			/**
			 * YubiKey details
			 */
			title: () => LocalizedString
			/**
			 * Download all keys
			 */
			downloadAll: () => LocalizedString
		}
		deleteUser: {
			/**
			 * Delete account
			 */
			title: () => LocalizedString
			controls: {
				/**
				 * Delete account
				 */
				submit: () => LocalizedString
			}
			/**
			 * Do you want to delete {username} account permanently ?
			 */
			message: (arg: { username: string }) => LocalizedString
			messages: {
				/**
				 * {username} deleted.
				 */
				success: (arg: { username: string }) => LocalizedString
			}
		}
		changeUserPassword: {
			messages: {
				/**
				 * Password changed.
				 */
				success: () => LocalizedString
			}
			/**
			 * Change user password
			 */
			title: () => LocalizedString
			form: {
				controls: {
					/**
					 * Save new password
					 */
					submit: () => LocalizedString
				}
				fields: {
					newPassword: {
						/**
						 * New password
						 */
						label: () => LocalizedString
					}
					confirmPassword: {
						/**
						 * Repeat password
						 */
						label: () => LocalizedString
					}
				}
			}
		}
		provisionKeys: {
			/**
			 * Yubikey provisioning:
			 */
			title: () => LocalizedString
			/**
			 * The selected provisioner must have a <b>clean</b> YubiKey
		                plugged in be provisioned. To clean a used YubiKey
		                <b>gpg-card factory reset</b> before provisioning.
			 */
			infoBox: () => LocalizedString
			/**
			 * Select one of the following provisioners to provision a YubiKey:
			 */
			selectionLabel: () => LocalizedString
			noData: {
				/**
				 * No workers found, waiting...
				 */
				workers: () => LocalizedString
			}
			controls: {
				/**
				 * Provision YubiKey
				 */
				submit: () => LocalizedString
			}
			messages: {
				/**
				 * Keys provisioned
				 */
				success: () => LocalizedString
				/**
				 * Error while getting worker status.
				 */
				errorStatus: () => LocalizedString
			}
		}
		addUser: {
			/**
			 * Add new user
			 */
			title: () => LocalizedString
			form: {
				/**
				 * Add user
				 */
				submit: () => LocalizedString
				fields: {
					username: {
						/**
						 * login
						 */
						placeholder: () => LocalizedString
						/**
						 * Login
						 */
						label: () => LocalizedString
					}
					password: {
						/**
						 * Password
						 */
						placeholder: () => LocalizedString
						/**
						 * Password
						 */
						label: () => LocalizedString
					}
					email: {
						/**
						 * User e-mail
						 */
						placeholder: () => LocalizedString
						/**
						 * User e-mail
						 */
						label: () => LocalizedString
					}
					firstName: {
						/**
						 * First name
						 */
						placeholder: () => LocalizedString
						/**
						 * First name
						 */
						label: () => LocalizedString
					}
					lastName: {
						/**
						 * Last name
						 */
						placeholder: () => LocalizedString
						/**
						 * Last name
						 */
						label: () => LocalizedString
					}
					phone: {
						/**
						 * Phone
						 */
						placeholder: () => LocalizedString
						/**
						 * Phone
						 */
						label: () => LocalizedString
					}
				}
			}
		}
	}
	userPage: {
		title: {
			/**
			 * User Profile
			 */
			view: () => LocalizedString
			/**
			 * Edit User Profile
			 */
			edit: () => LocalizedString
		}
		messages: {
			/**
			 * User updated.
			 */
			editSuccess: () => LocalizedString
		}
		userDetails: {
			/**
			 * Profile Details
			 */
			header: () => LocalizedString
			messages: {
				/**
				 * App and all tokens deleted.
				 */
				deleteApp: () => LocalizedString
			}
			fields: {
				username: {
					/**
					 * Username
					 */
					label: () => LocalizedString
				}
				firstName: {
					/**
					 * First name
					 */
					label: () => LocalizedString
				}
				lastName: {
					/**
					 * Last name
					 */
					label: () => LocalizedString
				}
				phone: {
					/**
					 * Phone number
					 */
					label: () => LocalizedString
				}
				email: {
					/**
					 * E-mail
					 */
					label: () => LocalizedString
				}
				groups: {
					/**
					 * User groups
					 */
					label: () => LocalizedString
					/**
					 * No groups
					 */
					noData: () => LocalizedString
				}
				apps: {
					/**
					 * Authorized apps
					 */
					label: () => LocalizedString
					/**
					 * No authorized apps
					 */
					noData: () => LocalizedString
				}
			}
		}
		userAuthInfo: {
			/**
			 * Password and authentication
			 */
			header: () => LocalizedString
			password: {
				/**
				 * Password settings
				 */
				header: () => LocalizedString
				/**
				 * Change password
				 */
				changePassword: () => LocalizedString
			}
			recovery: {
				/**
				 * Recovery options
				 */
				header: () => LocalizedString
				codes: {
					/**
					 * Recovery Codes
					 */
					label: () => LocalizedString
					/**
					 * Viewed
					 */
					viewed: () => LocalizedString
				}
			}
			mfa: {
				/**
				 * Two-factor methods
				 */
				header: () => LocalizedString
				edit: {
					/**
					 * Disable MFA
					 */
					disable: () => LocalizedString
				}
				messages: {
					/**
					 * MFA disabled.
					 */
					mfaDisabled: () => LocalizedString
					/**
					 * One time password disabled.
					 */
					OTPDisabled: () => LocalizedString
					/**
					 * MFA method changed
					 */
					changeMFAMethod: () => LocalizedString
				}
				securityKey: {
					/**
					 * security key
					 */
					singular: () => LocalizedString
					/**
					 * security keys
					 */
					plural: () => LocalizedString
				}
				/**
				 * default
				 */
				'default': () => LocalizedString
				/**
				 * Enabled
				 */
				enabled: () => LocalizedString
				/**
				 * Disabled
				 */
				disabled: () => LocalizedString
				wallet: {
					/**
					 * Wallet
					 */
					singular: () => LocalizedString
					/**
					 * Wallets
					 */
					plural: () => LocalizedString
				}
				labels: {
					/**
					 * Time based one time passwords
					 */
					totp: () => LocalizedString
					/**
					 * Security keys
					 */
					webauth: () => LocalizedString
					/**
					 * Wallets
					 */
					wallets: () => LocalizedString
				}
				editMode: {
					/**
					 * Enable
					 */
					enable: () => LocalizedString
					/**
					 * Disable
					 */
					disable: () => LocalizedString
					/**
					 * Make default
					 */
					makeDefault: () => LocalizedString
					webauth: {
						/**
						 * Manage security keys
						 */
						manage: () => LocalizedString
					}
				}
			}
		}
		controls: {
			/**
			 * Edit profile
			 */
			editButton: () => LocalizedString
			/**
			 * Delete account
			 */
			deleteAccount: () => LocalizedString
		}
		devices: {
			/**
			 * User devices
			 */
			header: () => LocalizedString
			addDevice: {
				/**
				 * Add new device
				 */
				web: () => LocalizedString
				/**
				 * Add this device
				 */
				desktop: () => LocalizedString
			}
			card: {
				labels: {
					/**
					 * Last location
					 */
					location: () => LocalizedString
					/**
					 * Last IP address
					 */
					lastIpAddress: () => LocalizedString
					/**
					 * Date added
					 */
					date: () => LocalizedString
				}
				edit: {
					/**
					 * Edit device
					 */
					edit: () => LocalizedString
					/**
					 * Download config
					 */
					download: () => LocalizedString
					/**
					 * Delete device
					 */
					'delete': () => LocalizedString
				}
			}
		}
		wallets: {
			messages: {
				duplicate: {
					/**
					 * Connected wallet is already registered
					 */
					primary: () => LocalizedString
					/**
					 * Please connect unused wallet.
					 */
					sub: () => LocalizedString
				}
			}
			/**
			 * User wallets
			 */
			header: () => LocalizedString
			/**
			 * Add new wallet
			 */
			addWallet: () => LocalizedString
			card: {
				/**
				 * Address
				 */
				address: () => LocalizedString
				/**
				 * MFA
				 */
				mfaBadge: () => LocalizedString
				edit: {
					/**
					 * Enable MFA
					 */
					enableMFA: () => LocalizedString
					/**
					 * Disable MFA
					 */
					disableMFA: () => LocalizedString
					/**
					 * Delete
					 */
					'delete': () => LocalizedString
				}
				messages: {
					/**
					 * Wallet deleted
					 */
					deleteSuccess: () => LocalizedString
					/**
					 * Wallet MFA enabled
					 */
					enableMFA: () => LocalizedString
					/**
					 * Wallet MFA disabled
					 */
					disableMFA: () => LocalizedString
				}
			}
		}
		yubiKey: {
			/**
			 * User YubiKey
			 */
			header: () => LocalizedString
			/**
			 * Provision a YubiKey
			 */
			provision: () => LocalizedString
			keys: {
				/**
				 * PGP key
				 */
				pgp: () => LocalizedString
				/**
				 * SSH key
				 */
				ssh: () => LocalizedString
			}
			noLicense: {
				/**
				 * YubiKey module
				 */
				moduleName: () => LocalizedString
				/**
				 * This is enterprise module for YubiKey
				 */
				line1: () => LocalizedString
				/**
				 * management and provisioning.
				 */
				line2: () => LocalizedString
			}
		}
	}
	usersOverview: {
		/**
		 * Users
		 */
		pageTitle: () => LocalizedString
		search: {
			/**
			 * Find users
			 */
			placeholder: () => LocalizedString
		}
		filterLabels: {
			/**
			 * All users
			 */
			all: () => LocalizedString
			/**
			 * Admins only
			 */
			admin: () => LocalizedString
			/**
			 * Users only
			 */
			users: () => LocalizedString
		}
		/**
		 * All users
		 */
		usersCount: () => LocalizedString
		/**
		 * Add new
		 */
		addNewUser: () => LocalizedString
		list: {
			headers: {
				/**
				 * User name
				 */
				name: () => LocalizedString
				/**
				 * Login
				 */
				username: () => LocalizedString
				/**
				 * Phone
				 */
				phone: () => LocalizedString
				/**
				 * Actions
				 */
				actions: () => LocalizedString
			}
			editButton: {
				/**
				 * Change password
				 */
				changePassword: () => LocalizedString
				/**
				 * Edit account
				 */
				edit: () => LocalizedString
				/**
				 * Provision YubiKey
				 */
				provision: () => LocalizedString
				/**
				 * Delete account
				 */
				'delete': () => LocalizedString
			}
		}
	}
	navigation: {
		bar: {
			/**
			 * Overview
			 */
			overview: () => LocalizedString
			/**
			 * Users
			 */
			users: () => LocalizedString
			/**
			 * Provisioners
			 */
			provisioners: () => LocalizedString
			/**
			 * Webhooks
			 */
			webhooks: () => LocalizedString
			/**
			 * OpenID Apps
			 */
			openId: () => LocalizedString
			/**
			 * My Profile
			 */
			myProfile: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
			/**
			 * Log out
			 */
			logOut: () => LocalizedString
		}
		mobileTitles: {
			/**
			 * Users
			 */
			users: () => LocalizedString
			/**
			 * Defguard Global Settings
			 */
			settings: () => LocalizedString
			/**
			 * User Profile
			 */
			user: () => LocalizedString
			/**
			 * Provisioners
			 */
			provisioners: () => LocalizedString
			/**
			 * Webhooks
			 */
			webhooks: () => LocalizedString
			/**
			 * OpenId Apps
			 */
			openId: () => LocalizedString
			/**
			 * Network Overview
			 */
			overview: () => LocalizedString
			/**
			 * Network Settings
			 */
			networkSettings: () => LocalizedString
		}
		/**
		 * Copyright © 2023
		 */
		copyright: () => LocalizedString
		/**
		 * Application version: {version}
		 */
		version: (arg: { version: string }) => LocalizedString
	}
	form: {
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Save changes
		 */
		saveChanges: () => LocalizedString
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		placeholders: {
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
		}
		error: {
			/**
			 * Username is already in use
			 */
			usernameTaken: () => LocalizedString
			/**
			 * Key is invalid.
			 */
			invalidKey: () => LocalizedString
			/**
			 * Field is invalid.
			 */
			invalid: () => LocalizedString
			/**
			 * Field is required.
			 */
			required: () => LocalizedString
			/**
			 * Maximum length exceeded.
			 */
			maximumLength: () => LocalizedString
			/**
			 * Minimum length not reached.
			 */
			minimumLength: () => LocalizedString
			/**
			 * No special characters are allowed.
			 */
			noSpecialChars: () => LocalizedString
			/**
			 * One digit required.
			 */
			oneDigit: () => LocalizedString
			/**
			 * Special character required.
			 */
			oneSpecial: () => LocalizedString
			/**
			 * One uppercase character required.
			 */
			oneUppercase: () => LocalizedString
			/**
			 * One lowercase character required.
			 */
			oneLowercase: () => LocalizedString
		}
	}
	components: {
		noLicenseBox: {
			footer: {
				/**
				 * Get an enterprise license
				 */
				get: () => LocalizedString
				/**
				 * by contacting:
				 */
				contact: () => LocalizedString
			}
		}
	}
	settingsPage: {
		/**
		 * Global Settings
		 */
		title: () => LocalizedString
		messages: {
			/**
			 * Error occured! Please contact administrator
			 */
			error: () => LocalizedString
			/**
			 * Settings updated
			 */
			editSuccess: () => LocalizedString
		}
		modulesVisibility: {
			/**
			 * Modules Visibility
			 */
			header: () => LocalizedString
			/**
			 * <p>
		            If your not using some modules you can disable their visibility.
		          </p>
		          <a href="defguard.gitbook.io" target="_blank">
		            Read more in documentation.
		          </a>
			 */
			helper: () => LocalizedString
			fields: {
				wireguard_enabled: {
					/**
					 * Wireguard VPN
					 */
					label: () => LocalizedString
				}
				webhooks_enabled: {
					/**
					 * Webhooks
					 */
					label: () => LocalizedString
				}
				web3_enabled: {
					/**
					 * Web3
					 */
					label: () => LocalizedString
				}
				worker_enabled: {
					/**
					 * YubiBridge
					 */
					label: () => LocalizedString
				}
				openid_enabled: {
					/**
					 * OpenID connect
					 */
					label: () => LocalizedString
				}
				oauth_enabled: {
					/**
					 * OAuth2
					 */
					label: () => LocalizedString
				}
			}
		}
		defaultNetworkSelect: {
			/**
			 * Default network view
			 */
			header: () => LocalizedString
			/**
			 * <p>Here you can change your default network view.</p>
		          <a href="defguard.gitbook.io" target="_blank">
		            Read more in documentation.
		          </a>
			 */
			helper: () => LocalizedString
		}
		web3Settings: {
			/**
			 * Web3 / Wallet connect
			 */
			header: () => LocalizedString
			fields: {
				signMessage: {
					/**
					 * Default sign message template
					 */
					label: () => LocalizedString
				}
			}
			controls: {
				/**
				 * Save changes
				 */
				save: () => LocalizedString
			}
		}
		instanceBranding: {
			/**
			 * Instance Branding
			 */
			header: () => LocalizedString
			form: {
				/**
				 * Name & Logo:
				 */
				title: () => LocalizedString
				fields: {
					instanceName: {
						/**
						 * Instance name
						 */
						label: () => LocalizedString
						/**
						 * Defguard
						 */
						placeholder: () => LocalizedString
					}
					mainLogoUrl: {
						/**
						 * Login logo url
						 */
						label: () => LocalizedString
						/**
						 * Default image
						 */
						placeholder: () => LocalizedString
					}
					navLogoUrl: {
						/**
						 * Navigation Logo url
						 */
						label: () => LocalizedString
						/**
						 * Default image
						 */
						placeholder: () => LocalizedString
					}
				}
				error: {
					/**
					 * Field is required
					 */
					required: () => LocalizedString
					/**
					 * Maximum length exceeded
					 */
					maximumLength: () => LocalizedString
					/**
					 * Should be at least 3 characters long
					 */
					minimumLength: () => LocalizedString
				}
				controls: {
					/**
					 * Restore default
					 */
					restoreDefault: () => LocalizedString
					/**
					 * Save changes
					 */
					submit: () => LocalizedString
				}
			}
			/**
			 * 
					      <p>
		            Here you can add url of your logo and name for your defguard
		            instance it will be displayed instead of defguard.
		          </p>
		          <a href="defguard.gitbook.io" target="_blank">
		            Read more in documentation.
		          </a>
				
			 */
			helper: () => LocalizedString
		}
		licenseCard: {
			/**
			 * License & Support Information
			 */
			header: () => LocalizedString
			licenseCardTitles: {
				/**
				 * Community
				 */
				community: () => LocalizedString
				/**
				 * Enterprise
				 */
				enterprise: () => LocalizedString
				/**
				 * license
				 */
				license: () => LocalizedString
			}
			body: {
				/**
				 * 
							<p> Thank you for purchasing enterprise license!</p>
							<br />
							<p>This includes following modules:</p>
				 */
				enterprise: () => LocalizedString
				/**
				 * 
			              <p>
			                You have our community license. If you wish to get Enterprise
			                license for full features set and support, please visit
			                <a href="https://defguard.net">https://defguard.net</a>
			              </p>
			              <br />
			              <p>Enterprise license includes:</p>
						
				 */
				community: () => LocalizedString
				/**
				 * read license agreement
				 */
				agreement: () => LocalizedString
				/**
				 * 
			          <ul>
			            <li>YubiBridge</li>
			            <li>OpenID</li>
			            <li>OpenLDAP</li>
			          </ul>
			          <br />
				 */
				modules: () => LocalizedString
			}
			footer: {
				/**
				 * licensed to: {company}
				 */
				company: (arg: { company: string }) => LocalizedString
				/**
				 * expiration date: {expiration}
				 */
				expiration: (arg: { expiration: string }) => LocalizedString
			}
		}
		supportCard: {
			/**
			 * Support
			 */
			title: () => LocalizedString
			body: {
				/**
				 * 
						<p>For Enterprise support</p>
			      <p>
			        Please contact: 
			        <a href="mailto:support@defguard.net">support@defguard.net</a>
			      </p>
						<br/>
			      <p>You can also visit our Community support:</p>
			      <a href="https://github.com/Defguard/defguard">
			        https://github.com/Defguard/defguard
			      </a>
					
				 */
				enterprise: () => LocalizedString
				/**
				 * <p>For Community support Please visit:</p>
			      <a href="https://github.com/Defguard/defguard">
			        https://github.com/Defguard/defguard
			      </a>
					
				 */
				community: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
