// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	messages: {
		/**
		 * E​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d​.
		 */
		error: string
		/**
		 * O​p​e​r​a​t​i​o​n​ ​s​u​c​c​e​e​d​e​d
		 */
		success: string
	}
	modals: {
		deleteUser: {
			/**
			 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
			 */
			title: string
			controls: {
				/**
				 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
				 */
				submit: string
			}
			/**
			 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​{​u​s​e​r​n​a​m​e​}​ ​a​c​c​o​u​n​t​ ​p​e​r​m​a​n​e​n​t​l​y​ ​?
			 * @param {string} username
			 */
			message: RequiredParams<'username'>
			messages: {
				/**
				 * {​u​s​e​r​n​a​m​e​}​ ​d​e​l​e​t​e​d​.
				 * @param {string} username
				 */
				success: RequiredParams<'username'>
			}
		}
		changeUserPassword: {
			messages: {
				/**
				 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​.
				 */
				success: string
			}
			/**
			 * C​h​a​n​g​e​ ​u​s​e​r​ ​p​a​s​s​w​o​r​d
			 */
			title: string
			form: {
				controls: {
					/**
					 * S​a​v​e​ ​n​e​w​ ​p​a​s​s​w​o​r​d
					 */
					submit: string
				}
				fields: {
					newPassword: {
						/**
						 * N​e​w​ ​p​a​s​s​w​o​r​d
						 */
						label: string
					}
					confirmPassword: {
						/**
						 * R​e​p​e​a​t​ ​p​a​s​s​w​o​r​d
						 */
						label: string
					}
				}
			}
		}
		provisionKeys: {
			/**
			 * Y​u​b​i​k​e​y​ ​p​r​o​v​i​s​i​o​n​i​n​g​:
			 */
			title: string
			/**
			 * T​h​e​ ​s​e​l​e​c​t​e​d​ ​p​r​o​v​i​s​i​o​n​e​r​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​<​b​>​c​l​e​a​n​<​/​b​>​ ​Y​u​b​i​K​e​y​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​p​l​u​g​g​e​d​ ​i​n​ ​b​e​ ​p​r​o​v​i​s​i​o​n​e​d​.​ ​T​o​ ​c​l​e​a​n​ ​a​ ​u​s​e​d​ ​Y​u​b​i​K​e​y​
		​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​ ​<​b​>​g​p​g​-​c​a​r​d​ ​f​a​c​t​o​r​y​ ​r​e​s​e​t​<​/​b​>​ ​b​e​f​o​r​e​ ​p​r​o​v​i​s​i​o​n​i​n​g​.
			 */
			infoBox: string
			/**
			 * S​e​l​e​c​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​p​r​o​v​i​s​i​o​n​e​r​s​ ​t​o​ ​p​r​o​v​i​s​i​o​n​ ​a​ ​Y​u​b​i​K​e​y​:
			 */
			selectionLabel: string
			noData: {
				/**
				 * N​o​ ​w​o​r​k​e​r​s​ ​f​o​u​n​d​,​ ​w​a​i​t​i​n​g​.​.​.
				 */
				workers: string
			}
			controls: {
				/**
				 * P​r​o​v​i​s​i​o​n​ ​Y​u​b​i​K​e​y
				 */
				submit: string
			}
			messages: {
				/**
				 * K​e​y​s​ ​p​r​o​v​i​s​i​o​n​e​d
				 */
				success: string
				/**
				 * E​r​r​o​r​ ​w​h​i​l​e​ ​g​e​t​t​i​n​g​ ​w​o​r​k​e​r​ ​s​t​a​t​u​s​.
				 */
				errorStatus: string
			}
		}
		addUser: {
			/**
			 * A​d​d​ ​n​e​w​ ​u​s​e​r
			 */
			title: string
			form: {
				/**
				 * A​d​d​ ​u​s​e​r
				 */
				submit: string
				fields: {
					username: {
						/**
						 * l​o​g​i​n
						 */
						placeholder: string
						/**
						 * L​o​g​i​n
						 */
						label: string
					}
					password: {
						/**
						 * P​a​s​s​w​o​r​d
						 */
						placeholder: string
						/**
						 * P​a​s​s​w​o​r​d
						 */
						label: string
					}
					email: {
						/**
						 * U​s​e​r​ ​e​-​m​a​i​l
						 */
						placeholder: string
						/**
						 * U​s​e​r​ ​e​-​m​a​i​l
						 */
						label: string
					}
					firstName: {
						/**
						 * F​i​r​s​t​ ​n​a​m​e
						 */
						placeholder: string
						/**
						 * F​i​r​s​t​ ​n​a​m​e
						 */
						label: string
					}
					lastName: {
						/**
						 * L​a​s​t​ ​n​a​m​e
						 */
						placeholder: string
						/**
						 * L​a​s​t​ ​n​a​m​e
						 */
						label: string
					}
					phone: {
						/**
						 * P​h​o​n​e
						 */
						placeholder: string
						/**
						 * P​h​o​n​e
						 */
						label: string
					}
				}
			}
		}
	}
	usersOverview: {
		/**
		 * U​s​e​r​s
		 */
		pageTitle: string
		search: {
			/**
			 * F​i​n​d​ ​u​s​e​r​s
			 */
			placeholder: string
		}
		filterLabels: {
			/**
			 * A​l​l​ ​u​s​e​r​s
			 */
			all: string
			/**
			 * A​d​m​i​n​s​ ​o​n​l​y
			 */
			admin: string
			/**
			 * U​s​e​r​s​ ​o​n​l​y
			 */
			users: string
		}
		/**
		 * A​l​l​ ​u​s​e​r​s
		 */
		usersCount: string
		/**
		 * A​d​d​ ​n​e​w
		 */
		addNewUser: string
		list: {
			headers: {
				/**
				 * U​s​e​r​ ​n​a​m​e
				 */
				name: string
				/**
				 * L​o​g​i​n
				 */
				username: string
				/**
				 * P​h​o​n​e
				 */
				phone: string
				/**
				 * A​c​t​i​o​n​s
				 */
				actions: string
			}
			editButton: {
				/**
				 * C​h​a​n​g​e​ ​p​a​s​s​w​o​r​d
				 */
				changePassword: string
				/**
				 * E​d​i​t​ ​a​c​c​o​u​n​t
				 */
				edit: string
				/**
				 * P​r​o​v​i​s​i​o​n​ ​Y​u​b​i​K​e​y
				 */
				provision: string
				/**
				 * D​e​l​e​t​e​ ​a​c​c​o​u​n​t
				 */
				'delete': string
			}
		}
	}
	navigation: {
		bar: {
			/**
			 * O​v​e​r​v​i​e​w
			 */
			overview: string
			/**
			 * U​s​e​r​s
			 */
			users: string
			/**
			 * P​r​o​v​i​s​i​o​n​e​r​s
			 */
			provisioners: string
			/**
			 * W​e​b​h​o​o​k​s
			 */
			webhooks: string
			/**
			 * O​p​e​n​I​D​ ​A​p​p​s
			 */
			openId: string
			/**
			 * M​y​ ​P​r​o​f​i​l​e
			 */
			myProfile: string
			/**
			 * S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * L​o​g​ ​o​u​t
			 */
			logOut: string
		}
		mobileTitles: {
			/**
			 * U​s​e​r​s
			 */
			users: string
			/**
			 * D​e​f​g​u​a​r​d​ ​G​l​o​b​a​l​ ​S​e​t​t​i​n​g​s
			 */
			settings: string
			/**
			 * U​s​e​r​ ​P​r​o​f​i​l​e
			 */
			user: string
			/**
			 * P​r​o​v​i​s​i​o​n​e​r​s
			 */
			provisioners: string
			/**
			 * W​e​b​h​o​o​k​s
			 */
			webhooks: string
			/**
			 * O​p​e​n​I​d​ ​A​p​p​s
			 */
			openId: string
			/**
			 * N​e​t​w​o​r​k​ ​O​v​e​r​v​i​e​w
			 */
			overview: string
			/**
			 * N​e​t​w​o​r​k​ ​S​e​t​t​i​n​g​s
			 */
			networkSettings: string
		}
		/**
		 * C​o​p​y​r​i​g​h​t​ ​©​ ​2​0​2​3
		 */
		copyright: string
		/**
		 * A​p​p​l​i​c​a​t​i​o​n​ ​v​e​r​s​i​o​n​:​ ​{​v​e​r​s​i​o​n​}
		 * @param {string} version
		 */
		version: RequiredParams<'version'>
	}
	form: {
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		placeholders: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
		}
		error: {
			/**
			 * U​s​e​r​n​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
			 */
			usernameTaken: string
			/**
			 * K​e​y​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			invalidKey: string
			/**
			 * F​i​e​l​d​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			invalid: string
			/**
			 * F​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d​.
			 */
			required: string
			/**
			 * M​a​x​i​m​u​m​ ​l​e​n​g​t​h​ ​e​x​c​e​e​d​e​d​.
			 */
			maximumLength: string
			/**
			 * M​i​n​i​m​u​m​ ​l​e​n​g​t​h​ ​n​o​t​ ​r​e​a​c​h​e​d​.
			 */
			minimumLength: string
			/**
			 * N​o​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​.
			 */
			noSpecialChars: string
			/**
			 * O​n​e​ ​d​i​g​i​t​ ​r​e​q​u​i​r​e​d​.
			 */
			oneDigit: string
			/**
			 * S​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneSpecial: string
			/**
			 * O​n​e​ ​u​p​p​e​r​c​a​s​e​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneUppercase: string
			/**
			 * O​n​e​ ​l​o​w​e​r​c​a​s​e​ ​c​h​a​r​a​c​t​e​r​ ​r​e​q​u​i​r​e​d​.
			 */
			oneLowercase: string
		}
	}
}

export type TranslationFunctions = {
	messages: {
		/**
		 * Error has occurred.
		 */
		error: () => LocalizedString
		/**
		 * Operation succeeded
		 */
		success: () => LocalizedString
	}
	modals: {
		deleteUser: {
			/**
			 * Delete account
			 */
			title: () => LocalizedString
			controls: {
				/**
				 * Delete account
				 */
				submit: () => LocalizedString
			}
			/**
			 * Do you want to delete {username} account permanently ?
			 */
			message: (arg: { username: string }) => LocalizedString
			messages: {
				/**
				 * {username} deleted.
				 */
				success: (arg: { username: string }) => LocalizedString
			}
		}
		changeUserPassword: {
			messages: {
				/**
				 * Password changed.
				 */
				success: () => LocalizedString
			}
			/**
			 * Change user password
			 */
			title: () => LocalizedString
			form: {
				controls: {
					/**
					 * Save new password
					 */
					submit: () => LocalizedString
				}
				fields: {
					newPassword: {
						/**
						 * New password
						 */
						label: () => LocalizedString
					}
					confirmPassword: {
						/**
						 * Repeat password
						 */
						label: () => LocalizedString
					}
				}
			}
		}
		provisionKeys: {
			/**
			 * Yubikey provisioning:
			 */
			title: () => LocalizedString
			/**
			 * The selected provisioner must have a <b>clean</b> YubiKey
		                plugged in be provisioned. To clean a used YubiKey
		                <b>gpg-card factory reset</b> before provisioning.
			 */
			infoBox: () => LocalizedString
			/**
			 * Select one of the following provisioners to provision a YubiKey:
			 */
			selectionLabel: () => LocalizedString
			noData: {
				/**
				 * No workers found, waiting...
				 */
				workers: () => LocalizedString
			}
			controls: {
				/**
				 * Provision YubiKey
				 */
				submit: () => LocalizedString
			}
			messages: {
				/**
				 * Keys provisioned
				 */
				success: () => LocalizedString
				/**
				 * Error while getting worker status.
				 */
				errorStatus: () => LocalizedString
			}
		}
		addUser: {
			/**
			 * Add new user
			 */
			title: () => LocalizedString
			form: {
				/**
				 * Add user
				 */
				submit: () => LocalizedString
				fields: {
					username: {
						/**
						 * login
						 */
						placeholder: () => LocalizedString
						/**
						 * Login
						 */
						label: () => LocalizedString
					}
					password: {
						/**
						 * Password
						 */
						placeholder: () => LocalizedString
						/**
						 * Password
						 */
						label: () => LocalizedString
					}
					email: {
						/**
						 * User e-mail
						 */
						placeholder: () => LocalizedString
						/**
						 * User e-mail
						 */
						label: () => LocalizedString
					}
					firstName: {
						/**
						 * First name
						 */
						placeholder: () => LocalizedString
						/**
						 * First name
						 */
						label: () => LocalizedString
					}
					lastName: {
						/**
						 * Last name
						 */
						placeholder: () => LocalizedString
						/**
						 * Last name
						 */
						label: () => LocalizedString
					}
					phone: {
						/**
						 * Phone
						 */
						placeholder: () => LocalizedString
						/**
						 * Phone
						 */
						label: () => LocalizedString
					}
				}
			}
		}
	}
	usersOverview: {
		/**
		 * Users
		 */
		pageTitle: () => LocalizedString
		search: {
			/**
			 * Find users
			 */
			placeholder: () => LocalizedString
		}
		filterLabels: {
			/**
			 * All users
			 */
			all: () => LocalizedString
			/**
			 * Admins only
			 */
			admin: () => LocalizedString
			/**
			 * Users only
			 */
			users: () => LocalizedString
		}
		/**
		 * All users
		 */
		usersCount: () => LocalizedString
		/**
		 * Add new
		 */
		addNewUser: () => LocalizedString
		list: {
			headers: {
				/**
				 * User name
				 */
				name: () => LocalizedString
				/**
				 * Login
				 */
				username: () => LocalizedString
				/**
				 * Phone
				 */
				phone: () => LocalizedString
				/**
				 * Actions
				 */
				actions: () => LocalizedString
			}
			editButton: {
				/**
				 * Change password
				 */
				changePassword: () => LocalizedString
				/**
				 * Edit account
				 */
				edit: () => LocalizedString
				/**
				 * Provision YubiKey
				 */
				provision: () => LocalizedString
				/**
				 * Delete account
				 */
				'delete': () => LocalizedString
			}
		}
	}
	navigation: {
		bar: {
			/**
			 * Overview
			 */
			overview: () => LocalizedString
			/**
			 * Users
			 */
			users: () => LocalizedString
			/**
			 * Provisioners
			 */
			provisioners: () => LocalizedString
			/**
			 * Webhooks
			 */
			webhooks: () => LocalizedString
			/**
			 * OpenID Apps
			 */
			openId: () => LocalizedString
			/**
			 * My Profile
			 */
			myProfile: () => LocalizedString
			/**
			 * Settings
			 */
			settings: () => LocalizedString
			/**
			 * Log out
			 */
			logOut: () => LocalizedString
		}
		mobileTitles: {
			/**
			 * Users
			 */
			users: () => LocalizedString
			/**
			 * Defguard Global Settings
			 */
			settings: () => LocalizedString
			/**
			 * User Profile
			 */
			user: () => LocalizedString
			/**
			 * Provisioners
			 */
			provisioners: () => LocalizedString
			/**
			 * Webhooks
			 */
			webhooks: () => LocalizedString
			/**
			 * OpenId Apps
			 */
			openId: () => LocalizedString
			/**
			 * Network Overview
			 */
			overview: () => LocalizedString
			/**
			 * Network Settings
			 */
			networkSettings: () => LocalizedString
		}
		/**
		 * Copyright © 2023
		 */
		copyright: () => LocalizedString
		/**
		 * Application version: {version}
		 */
		version: (arg: { version: string }) => LocalizedString
	}
	form: {
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		placeholders: {
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
		}
		error: {
			/**
			 * Username is already in use
			 */
			usernameTaken: () => LocalizedString
			/**
			 * Key is invalid.
			 */
			invalidKey: () => LocalizedString
			/**
			 * Field is invalid.
			 */
			invalid: () => LocalizedString
			/**
			 * Field is required.
			 */
			required: () => LocalizedString
			/**
			 * Maximum length exceeded.
			 */
			maximumLength: () => LocalizedString
			/**
			 * Minimum length not reached.
			 */
			minimumLength: () => LocalizedString
			/**
			 * No special characters are allowed.
			 */
			noSpecialChars: () => LocalizedString
			/**
			 * One digit required.
			 */
			oneDigit: () => LocalizedString
			/**
			 * Special character required.
			 */
			oneSpecial: () => LocalizedString
			/**
			 * One uppercase character required.
			 */
			oneUppercase: () => LocalizedString
			/**
			 * One lowercase character required.
			 */
			oneLowercase: () => LocalizedString
		}
	}
}

export type Formatters = {}
