apiVersion: v1
kind: Secret
metadata:
  name: "gh-actions-deploy-service-account-token"
  namespace: "defguard-dev"
  annotations:
    kubernetes.io/service-account.name: "gh-actions-deploy"
type: kubernetes.io/service-account-token

