ALTER TABLE settings DROP COLUMN gateway_disconnect_notifications_enabled;
ALTER TABLE settings DROP COLUMN gateway_disconnect_notifications_inactivity_threshold;
ALTER TABLE settings DROP COLUMN gateway_disconnect_notifications_reconnect_notification_enabled;
