CREATE TABLE mail_context (
    template TEXT NOT NULL,
    section TEXT NOT NULL,
    language_tag TEXT NOT NULL,
    text TEXT NOT NULL,
    CONSTRAINT template_section_language UNIQUE (template, section, language_tag)
);
INSERT INTO mail_context (template, section, language_tag, text) VALUES
    ('desktop-start', 'title', 'en_US', 'You''re receiving this email to configure a new desktop client.'),
    ('desktop-start', 'subtitle', 'en_US', 'Please paste this URL and token in your desktop client:'),
    ('desktop-start', 'label_url', 'en_US', 'URL'),
    ('desktop-start', 'label_token', 'en_US', 'Token'),
    ('desktop-start', 'configure', 'en_US', 'Configure your desktop client'),
    ('desktop-start', 'click', 'en_US', 'Click the button or use link below'),
    ('new-account', 'title', 'en_US', 'New account has been created for you'),
    ('new-account', 'subtitle', 'en_US', 'To start the enrollment process, please use credentials below.'),
    ('new-account', 'download', 'en_US', 'Download the official Defguard desktop client for your system.'),
    ('new-account', 'after_install', 'en_US', 'After installation, please add a Defguard instance by entering:'),
    ('new-account', 'label_url', 'en_US', 'URL'),
    ('new-account', 'label_token', 'en_US', 'Token'),
    ('new-account', 'token_info', 'en_US', 'The token is valid for 24 hours. Once the enrollment process starts, you have 10 minutes to complete it.'),
    ('new-account', 'label_enroll', 'en_US', 'Enroll with desktop client'),
    ('new-account', 'label_mobile', 'en_US', 'Mobile application'),
    ('new-account', 'scan_qr', 'en_US', 'Scan QR code below to activate Defguard mobile application.'),
    ('new-account', 'mobile_install', 'en_US', 'If you haven''t installed the mobile app, click one of the buttons below.'),
    ('new-account', 'download_google', 'en_US', 'Download from Google Play'),
    ('new-account', 'download_apple', 'en_US', 'Download from Apple Store'),
    ('new-device', 'title', 'en_US', 'A new device has been added to your account:'),
    ('new-device', 'label_device', 'en_US', 'Device name'),
    ('new-device', 'label_pubkey', 'en_US', 'Public key'),
    ('mfa-code', 'title', 'en_US', 'Hello,'),
    ('mfa-code', 'subtitle', 'en_US', 'It seems like you are trying to login to Defguard. Here is the code you need to access your account.'),
    ('mfa-code', 'code_is_valid', 'en_US', 'The code is valid for 1 minute');
