INSERT INTO mail_context (template, section, language_tag, text) VALUES
    ('mfa-activation', 'title', 'en_US', 'Hello,'),
    ('mfa-activation', 'subtitle', 'en_US', 'You are activating Multi-Factor Authentication using email verification codes.'),
    ('mfa-activation', 'code_is_valid', 'en_US', 'The code is valid for:'),
    ('enrollment-admin-notification', 'title', 'en_US', 'Dear,'),
    ('enrollment-admin-notification', 'message', 'en_US', 'just completed their enrollment process.'),
    ('enrollment-admin-notification', 'goodday', 'en_US', 'Have a good day!'),
    ('gateway-disconnect', 'title', 'en_US', 'Defguard Gateway has just disconnected.'),
    ('gateway-disconnect', 'subtitle', 'en_US', 'Please login to your gateway server and see the logs.'),
    ('gateway-disconnect', 'gateway_label', 'en_US', 'Gateway name:'),
    ('gateway-disconnect', 'ip_address_label', 'en_US', 'Gateway IP address:'),
    ('gateway-disconnect', 'location_label', 'en_US', 'VPN location:'),
    ('gateway-reconnect', 'title', 'en_US', 'Defguard Gateway has just disconnected.'),
    ('gateway-reconnect', 'gateway_label', 'en_US', 'Gateway name:'),
    ('gateway-reconnect', 'ip_address_label', 'en_US', 'Gateway IP address:'),
    ('gateway-reconnect', 'location_label', 'en_US', 'VPN location:'),
    ('mfa-configured', 'title', 'en_US', 'Hello,'),
    ('mfa-configured', 'subtitle', 'en_US', 'A Multi-Factor Authentication (MFA) has been activated in your account.'),
    ('mfa-configured', 'mfa_method_label', 'en_US', 'MFA method:'),
    ('new-device-login', 'title', 'en_US', 'Your account was just logged into from a new device.'),
    ('new-device-login', 'label_device', 'en_US', 'Device name:'),
    ('new-device-login', 'label_date', 'en_US', 'Date:'),
    ('new-device-oidc-login', 'title', 'en_US', 'Your account was just logged into a system using OpenID Connect authorization'),
    ('new-device-oidc-login', 'subtitle', 'en_US', 'You can deauthorize all applications that have access to your account from the web vault under (My Profile > Apps).'),
    ('new-device-oidc-login', 'label_profile', 'en_US', 'Profile URL:'),
    ('new-device-oidc-login', 'label_oauth2client', 'en_US', 'System name:'),
    ('password-reset', 'title', 'en_US', 'Password reset'),
    ('password-reset', 'subtitle', 'en_US', 'If you wish to reset your password, please copy and paste the following URL in your browser:'),
    ('password-reset-done', 'title', 'en_US', 'Password reset'),
    ('password-reset-done', 'subtitle', 'en_US', 'Your password has been successfully changed.'),
    ('test', 'title', 'en_US', 'This is test email from Defguard system.'),
    ('test', 'subtitle', 'en_US', 'If you received it, your SMTP configuration is correct.'),
    ('support-data', 'title', 'en_US', 'Support data'),
    ('support-data', 'subtitle', 'en_US', 'Support data can be found in the attachment.');
