ALTER TABLE aclrule
  DROP COLUMN any_destination,
  DROP COLUMN any_port,
  DROP COLUMN any_protocol,
  DROP COLUMN manual_settings;
ALTER TABLE aclalias
  DROP COLUMN any_destination,
  DROP COLUMN any_port,
  DROP COLUMN any_protocol;
