INSERT INTO mail_context (template, section, language_tag, text) VALUES
    ('mfa-activation', 'title', 'en_US', 'Hello,'),
    ('mfa-activation', 'subtitle', 'en_US', 'You are activating Multi-Factor Authentication using email verification codes.'),
    ('mfa-activation', 'code_is_valid', 'en_US', 'The code is valid for:'),
    ('enrollment-admin-notification', 'title', 'en_US', 'Dear,'),
    ('enrollment-admin-notification', 'message', 'en_US', 'just completed their enrollment process.'),
    ('enrollment-admin-notification', 'goodday', 'en_US', 'Have a good day!'),
    ('gateway-disconnect', 'title', 'en_US', 'Defguard Gateway has just disconnected.'),
    ('gateway-disconnect', 'subtitle', 'en_US', 'Please login to your gateway server and see the logs.'),
    ('gateway-disconnect', 'gateway_label', 'en_US', 'Gateway name:'),
    ('gateway-disconnect', 'ip_address_label', 'en_US', 'Gateway IP address:'),
    ('gateway-disconnect', 'location_label', 'en_US', 'VPN location:'),
    ('gateway-reconnect', 'title', 'en_US', 'Defguard Gateway has just disconnected.'),
    ('gateway-reconnect', 'gateway_label', 'en_US', 'Gateway name:'),
    ('gateway-reconnect', 'ip_address_label', 'en_US', 'Gateway IP address:'),
    ('gateway-reconnect', 'location_label', 'en_US', 'VPN location:');
