apiVersion: v1
kind: Service
metadata:
  labels:
    app: orion
    service: frontend
  name: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: orion
    service: frontend
