apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: orion
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
      service: frontend
  template:
    metadata:
      labels:
        app: orion
        service: frontend
    spec:
      containers:
        - name: frontend
          image: registry.teonite.net/defguard/frontend:latest
          ports:
            - containerPort: 80
