#!/bin/sh

# PROVIDE: defguard
# REQUIRE: NETWORKING wireguard
# KEYWORD: shutdown

. /etc/rc.subr

name="defguard"
rcvar=defguard_enable
command="/usr/local/bin/defguard"
defguard_env_file="/etc/defguard/core.conf"
start_cmd="${name}_start"

defguard_start() {
	${command} &
}

load_rc_config $name
run_rc_command "$1"
