[sources.my_http_source]
type = "http_server"
address = "0.0.0.0:8001"
encoding = "ndjson"

[sources.my_http_source.tls]
enabled = false

[sources.my_http_source.auth]
strategy = "basic"
password = "pass123"
username = "vector"


[sinks.console]
type = "console"
inputs = ["my_http_source"]
target = "stdout"
encoding.codec = "json"

