[package]
name = "defguard_version"
version = "0.0.0"
edition.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
semver.workspace = true
thiserror.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tonic-middleware.workspace = true
http = "1.3.1"
os_info = "3.12.0"
tower = "0.5.2"
