/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthMfaWebauthnRouteImport } from './routes/auth/mfa/webauthn'
import { Route as AuthMfaTotpRouteImport } from './routes/auth/mfa/totp'
import { Route as AuthMfaRecoveryRouteImport } from './routes/auth/mfa/recovery'
import { Route as AuthMfaEmailRouteImport } from './routes/auth/mfa/email'
import { Route as AuthorizedUserUsernameRouteImport } from './routes/_authorized/user/$username'

const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaWebauthnRoute = AuthMfaWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaTotpRoute = AuthMfaTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaRecoveryRoute = AuthMfaRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaEmailRoute = AuthMfaEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthorizedUserUsernameRoute = AuthorizedUserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => AuthorizedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/user/$username': typeof AuthorizedUserUsernameRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/user/$username': typeof AuthorizedUserUsernameRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_authorized/user/$username': typeof AuthorizedUserUsernameRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth'
    | '/user/$username'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth'
    | '/user/$username'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/'
    | '/_authorized/user/$username'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa/webauthn': {
      id: '/auth/mfa/webauthn'
      path: '/webauthn'
      fullPath: '/auth/mfa/webauthn'
      preLoaderRoute: typeof AuthMfaWebauthnRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/totp': {
      id: '/auth/mfa/totp'
      path: '/totp'
      fullPath: '/auth/mfa/totp'
      preLoaderRoute: typeof AuthMfaTotpRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/recovery': {
      id: '/auth/mfa/recovery'
      path: '/recovery'
      fullPath: '/auth/mfa/recovery'
      preLoaderRoute: typeof AuthMfaRecoveryRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/email': {
      id: '/auth/mfa/email'
      path: '/email'
      fullPath: '/auth/mfa/email'
      preLoaderRoute: typeof AuthMfaEmailRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/_authorized/user/$username': {
      id: '/_authorized/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AuthorizedUserUsernameRouteImport
      parentRoute: typeof AuthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedUserUsernameRoute: typeof AuthorizedUserUsernameRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedUserUsernameRoute: AuthorizedUserUsernameRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

interface AuthMfaRouteChildren {
  AuthMfaEmailRoute: typeof AuthMfaEmailRoute
  AuthMfaRecoveryRoute: typeof AuthMfaRecoveryRoute
  AuthMfaTotpRoute: typeof AuthMfaTotpRoute
  AuthMfaWebauthnRoute: typeof AuthMfaWebauthnRoute
}

const AuthMfaRouteChildren: AuthMfaRouteChildren = {
  AuthMfaEmailRoute: AuthMfaEmailRoute,
  AuthMfaRecoveryRoute: AuthMfaRecoveryRoute,
  AuthMfaTotpRoute: AuthMfaTotpRoute,
  AuthMfaWebauthnRoute: AuthMfaWebauthnRoute,
}

const AuthMfaRouteWithChildren =
  AuthMfaRoute._addFileChildren(AuthMfaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRoute: AuthorizedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
