/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnackbarRouteImport } from './routes/snackbar'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLoadingRouteImport } from './routes/auth/loading'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as WizardSetupLoginRouteImport } from './routes/_wizard/setup-login'
import { Route as WizardSetupRouteImport } from './routes/_wizard/setup'
import { Route as AuthorizedPlaygroundRouteImport } from './routes/_authorized/playground'
import { Route as AuthorizedDefaultRouteImport } from './routes/_authorized/_default'
import { Route as AuthMfaWebauthnRouteImport } from './routes/auth/mfa/webauthn'
import { Route as AuthMfaTotpRouteImport } from './routes/auth/mfa/totp'
import { Route as AuthMfaRecoveryRouteImport } from './routes/auth/mfa/recovery'
import { Route as AuthMfaEmailRouteImport } from './routes/auth/mfa/email'
import { Route as AuthorizedWizardSetupGatewayRouteImport } from './routes/_authorized/_wizard/setup-gateway'
import { Route as AuthorizedWizardSetupEdgeRouteImport } from './routes/_authorized/_wizard/setup-edge'
import { Route as AuthorizedWizardAddLocationRouteImport } from './routes/_authorized/_wizard/add-location'
import { Route as AuthorizedWizardAddExternalOpenidRouteImport } from './routes/_authorized/_wizard/add-external-openid'
import { Route as AuthorizedDefaultWebhooksRouteImport } from './routes/_authorized/_default/webhooks'
import { Route as AuthorizedDefaultUsersRouteImport } from './routes/_authorized/_default/users'
import { Route as AuthorizedDefaultOpenidRouteImport } from './routes/_authorized/_default/openid'
import { Route as AuthorizedDefaultNetworkDevicesRouteImport } from './routes/_authorized/_default/network-devices'
import { Route as AuthorizedDefaultGroupsRouteImport } from './routes/_authorized/_default/groups'
import { Route as AuthorizedDefaultEdgesRouteImport } from './routes/_authorized/_default/edges'
import { Route as AuthorizedDefaultActivityRouteImport } from './routes/_authorized/_default/activity'
import { Route as AuthorizedDefaultVpnOverviewIndexRouteImport } from './routes/_authorized/_default/vpn-overview/index'
import { Route as AuthorizedDefaultSettingsIndexRouteImport } from './routes/_authorized/_default/settings/index'
import { Route as AuthorizedDefaultLocationsIndexRouteImport } from './routes/_authorized/_default/locations/index'
import { Route as AuthorizedDefaultVpnOverviewLocationIdRouteImport } from './routes/_authorized/_default/vpn-overview/$locationId'
import { Route as AuthorizedDefaultUserUsernameRouteImport } from './routes/_authorized/_default/user/$username'
import { Route as AuthorizedDefaultSettingsSmtpRouteImport } from './routes/_authorized/_default/settings/smtp'
import { Route as AuthorizedDefaultSettingsOpenidRouteImport } from './routes/_authorized/_default/settings/openid'
import { Route as AuthorizedDefaultSettingsLdapRouteImport } from './routes/_authorized/_default/settings/ldap'
import { Route as AuthorizedDefaultSettingsInstanceRouteImport } from './routes/_authorized/_default/settings/instance'
import { Route as AuthorizedDefaultSettingsGatewayNotificationsRouteImport } from './routes/_authorized/_default/settings/gateway-notifications'
import { Route as AuthorizedDefaultSettingsEditOpenidRouteImport } from './routes/_authorized/_default/settings/edit-openid'
import { Route as AuthorizedDefaultSettingsClientRouteImport } from './routes/_authorized/_default/settings/client'
import { Route as AuthorizedDefaultAclRulesRouteImport } from './routes/_authorized/_default/acl/rules'
import { Route as AuthorizedDefaultAclEditRuleRouteImport } from './routes/_authorized/_default/acl/edit-rule'
import { Route as AuthorizedDefaultAclEditDestinationRouteImport } from './routes/_authorized/_default/acl/edit-destination'
import { Route as AuthorizedDefaultAclEditAliasRouteImport } from './routes/_authorized/_default/acl/edit-alias'
import { Route as AuthorizedDefaultAclDestinationsRouteImport } from './routes/_authorized/_default/acl/destinations'
import { Route as AuthorizedDefaultAclAliasesRouteImport } from './routes/_authorized/_default/acl/aliases'
import { Route as AuthorizedDefaultAclAddRuleRouteImport } from './routes/_authorized/_default/acl/add-rule'
import { Route as AuthorizedDefaultAclAddDestinationRouteImport } from './routes/_authorized/_default/acl/add-destination'
import { Route as AuthorizedDefaultAclAddAliasRouteImport } from './routes/_authorized/_default/acl/add-alias'
import { Route as AuthorizedDefaultLocationsLocationIdEditRouteImport } from './routes/_authorized/_default/locations/$locationId/edit'
import { Route as AuthorizedDefaultEdgeEdgeIdEditRouteImport } from './routes/_authorized/_default/edge/$edgeId/edit'

const SnackbarRoute = SnackbarRouteImport.update({
  id: '/snackbar',
  path: '/snackbar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoadingRoute = AuthLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const WizardSetupLoginRoute = WizardSetupLoginRouteImport.update({
  id: '/_wizard/setup-login',
  path: '/setup-login',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardSetupRoute = WizardSetupRouteImport.update({
  id: '/_wizard/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedPlaygroundRoute = AuthorizedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthorizedDefaultRoute = AuthorizedDefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => AuthorizedRoute,
} as any)
const AuthMfaWebauthnRoute = AuthMfaWebauthnRouteImport.update({
  id: '/webauthn',
  path: '/webauthn',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaTotpRoute = AuthMfaTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaRecoveryRoute = AuthMfaRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthMfaEmailRoute = AuthMfaEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthMfaRoute,
} as any)
const AuthorizedWizardSetupGatewayRoute =
  AuthorizedWizardSetupGatewayRouteImport.update({
    id: '/_wizard/setup-gateway',
    path: '/setup-gateway',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedWizardSetupEdgeRoute =
  AuthorizedWizardSetupEdgeRouteImport.update({
    id: '/_wizard/setup-edge',
    path: '/setup-edge',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedWizardAddLocationRoute =
  AuthorizedWizardAddLocationRouteImport.update({
    id: '/_wizard/add-location',
    path: '/add-location',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedWizardAddExternalOpenidRoute =
  AuthorizedWizardAddExternalOpenidRouteImport.update({
    id: '/_wizard/add-external-openid',
    path: '/add-external-openid',
    getParentRoute: () => AuthorizedRoute,
  } as any)
const AuthorizedDefaultWebhooksRoute =
  AuthorizedDefaultWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultUsersRoute = AuthorizedDefaultUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthorizedDefaultRoute,
} as any)
const AuthorizedDefaultOpenidRoute = AuthorizedDefaultOpenidRouteImport.update({
  id: '/openid',
  path: '/openid',
  getParentRoute: () => AuthorizedDefaultRoute,
} as any)
const AuthorizedDefaultNetworkDevicesRoute =
  AuthorizedDefaultNetworkDevicesRouteImport.update({
    id: '/network-devices',
    path: '/network-devices',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultGroupsRoute = AuthorizedDefaultGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthorizedDefaultRoute,
} as any)
const AuthorizedDefaultEdgesRoute = AuthorizedDefaultEdgesRouteImport.update({
  id: '/edges',
  path: '/edges',
  getParentRoute: () => AuthorizedDefaultRoute,
} as any)
const AuthorizedDefaultActivityRoute =
  AuthorizedDefaultActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultVpnOverviewIndexRoute =
  AuthorizedDefaultVpnOverviewIndexRouteImport.update({
    id: '/vpn-overview/',
    path: '/vpn-overview/',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsIndexRoute =
  AuthorizedDefaultSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultLocationsIndexRoute =
  AuthorizedDefaultLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultVpnOverviewLocationIdRoute =
  AuthorizedDefaultVpnOverviewLocationIdRouteImport.update({
    id: '/vpn-overview/$locationId',
    path: '/vpn-overview/$locationId',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultUserUsernameRoute =
  AuthorizedDefaultUserUsernameRouteImport.update({
    id: '/user/$username',
    path: '/user/$username',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsSmtpRoute =
  AuthorizedDefaultSettingsSmtpRouteImport.update({
    id: '/settings/smtp',
    path: '/settings/smtp',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsOpenidRoute =
  AuthorizedDefaultSettingsOpenidRouteImport.update({
    id: '/settings/openid',
    path: '/settings/openid',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsLdapRoute =
  AuthorizedDefaultSettingsLdapRouteImport.update({
    id: '/settings/ldap',
    path: '/settings/ldap',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsInstanceRoute =
  AuthorizedDefaultSettingsInstanceRouteImport.update({
    id: '/settings/instance',
    path: '/settings/instance',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsGatewayNotificationsRoute =
  AuthorizedDefaultSettingsGatewayNotificationsRouteImport.update({
    id: '/settings/gateway-notifications',
    path: '/settings/gateway-notifications',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsEditOpenidRoute =
  AuthorizedDefaultSettingsEditOpenidRouteImport.update({
    id: '/settings/edit-openid',
    path: '/settings/edit-openid',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultSettingsClientRoute =
  AuthorizedDefaultSettingsClientRouteImport.update({
    id: '/settings/client',
    path: '/settings/client',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclRulesRoute =
  AuthorizedDefaultAclRulesRouteImport.update({
    id: '/acl/rules',
    path: '/acl/rules',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclEditRuleRoute =
  AuthorizedDefaultAclEditRuleRouteImport.update({
    id: '/acl/edit-rule',
    path: '/acl/edit-rule',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclEditDestinationRoute =
  AuthorizedDefaultAclEditDestinationRouteImport.update({
    id: '/acl/edit-destination',
    path: '/acl/edit-destination',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclEditAliasRoute =
  AuthorizedDefaultAclEditAliasRouteImport.update({
    id: '/acl/edit-alias',
    path: '/acl/edit-alias',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclDestinationsRoute =
  AuthorizedDefaultAclDestinationsRouteImport.update({
    id: '/acl/destinations',
    path: '/acl/destinations',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclAliasesRoute =
  AuthorizedDefaultAclAliasesRouteImport.update({
    id: '/acl/aliases',
    path: '/acl/aliases',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclAddRuleRoute =
  AuthorizedDefaultAclAddRuleRouteImport.update({
    id: '/acl/add-rule',
    path: '/acl/add-rule',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclAddDestinationRoute =
  AuthorizedDefaultAclAddDestinationRouteImport.update({
    id: '/acl/add-destination',
    path: '/acl/add-destination',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultAclAddAliasRoute =
  AuthorizedDefaultAclAddAliasRouteImport.update({
    id: '/acl/add-alias',
    path: '/acl/add-alias',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultLocationsLocationIdEditRoute =
  AuthorizedDefaultLocationsLocationIdEditRouteImport.update({
    id: '/locations/$locationId/edit',
    path: '/locations/$locationId/edit',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)
const AuthorizedDefaultEdgeEdgeIdEditRoute =
  AuthorizedDefaultEdgeEdgeIdEditRouteImport.update({
    id: '/edge/$edgeId/edit',
    path: '/edge/$edgeId/edit',
    getParentRoute: () => AuthorizedDefaultRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof AuthorizedDefaultRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/consent': typeof ConsentRoute
  '/snackbar': typeof SnackbarRoute
  '/playground': typeof AuthorizedPlaygroundRoute
  '/setup': typeof WizardSetupRoute
  '/setup-login': typeof WizardSetupLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/loading': typeof AuthLoadingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/activity': typeof AuthorizedDefaultActivityRoute
  '/edges': typeof AuthorizedDefaultEdgesRoute
  '/groups': typeof AuthorizedDefaultGroupsRoute
  '/network-devices': typeof AuthorizedDefaultNetworkDevicesRoute
  '/openid': typeof AuthorizedDefaultOpenidRoute
  '/users': typeof AuthorizedDefaultUsersRoute
  '/webhooks': typeof AuthorizedDefaultWebhooksRoute
  '/add-external-openid': typeof AuthorizedWizardAddExternalOpenidRoute
  '/add-location': typeof AuthorizedWizardAddLocationRoute
  '/setup-edge': typeof AuthorizedWizardSetupEdgeRoute
  '/setup-gateway': typeof AuthorizedWizardSetupGatewayRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
  '/acl/add-alias': typeof AuthorizedDefaultAclAddAliasRoute
  '/acl/add-destination': typeof AuthorizedDefaultAclAddDestinationRoute
  '/acl/add-rule': typeof AuthorizedDefaultAclAddRuleRoute
  '/acl/aliases': typeof AuthorizedDefaultAclAliasesRoute
  '/acl/destinations': typeof AuthorizedDefaultAclDestinationsRoute
  '/acl/edit-alias': typeof AuthorizedDefaultAclEditAliasRoute
  '/acl/edit-destination': typeof AuthorizedDefaultAclEditDestinationRoute
  '/acl/edit-rule': typeof AuthorizedDefaultAclEditRuleRoute
  '/acl/rules': typeof AuthorizedDefaultAclRulesRoute
  '/settings/client': typeof AuthorizedDefaultSettingsClientRoute
  '/settings/edit-openid': typeof AuthorizedDefaultSettingsEditOpenidRoute
  '/settings/gateway-notifications': typeof AuthorizedDefaultSettingsGatewayNotificationsRoute
  '/settings/instance': typeof AuthorizedDefaultSettingsInstanceRoute
  '/settings/ldap': typeof AuthorizedDefaultSettingsLdapRoute
  '/settings/openid': typeof AuthorizedDefaultSettingsOpenidRoute
  '/settings/smtp': typeof AuthorizedDefaultSettingsSmtpRoute
  '/user/$username': typeof AuthorizedDefaultUserUsernameRoute
  '/vpn-overview/$locationId': typeof AuthorizedDefaultVpnOverviewLocationIdRoute
  '/locations/': typeof AuthorizedDefaultLocationsIndexRoute
  '/settings/': typeof AuthorizedDefaultSettingsIndexRoute
  '/vpn-overview/': typeof AuthorizedDefaultVpnOverviewIndexRoute
  '/edge/$edgeId/edit': typeof AuthorizedDefaultEdgeEdgeIdEditRoute
  '/locations/$locationId/edit': typeof AuthorizedDefaultLocationsLocationIdEditRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/': typeof AuthorizedDefaultRouteWithChildren
  '/consent': typeof ConsentRoute
  '/snackbar': typeof SnackbarRoute
  '/playground': typeof AuthorizedPlaygroundRoute
  '/setup': typeof WizardSetupRoute
  '/setup-login': typeof WizardSetupLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/loading': typeof AuthLoadingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/activity': typeof AuthorizedDefaultActivityRoute
  '/edges': typeof AuthorizedDefaultEdgesRoute
  '/groups': typeof AuthorizedDefaultGroupsRoute
  '/network-devices': typeof AuthorizedDefaultNetworkDevicesRoute
  '/openid': typeof AuthorizedDefaultOpenidRoute
  '/users': typeof AuthorizedDefaultUsersRoute
  '/webhooks': typeof AuthorizedDefaultWebhooksRoute
  '/add-external-openid': typeof AuthorizedWizardAddExternalOpenidRoute
  '/add-location': typeof AuthorizedWizardAddLocationRoute
  '/setup-edge': typeof AuthorizedWizardSetupEdgeRoute
  '/setup-gateway': typeof AuthorizedWizardSetupGatewayRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
  '/acl/add-alias': typeof AuthorizedDefaultAclAddAliasRoute
  '/acl/add-destination': typeof AuthorizedDefaultAclAddDestinationRoute
  '/acl/add-rule': typeof AuthorizedDefaultAclAddRuleRoute
  '/acl/aliases': typeof AuthorizedDefaultAclAliasesRoute
  '/acl/destinations': typeof AuthorizedDefaultAclDestinationsRoute
  '/acl/edit-alias': typeof AuthorizedDefaultAclEditAliasRoute
  '/acl/edit-destination': typeof AuthorizedDefaultAclEditDestinationRoute
  '/acl/edit-rule': typeof AuthorizedDefaultAclEditRuleRoute
  '/acl/rules': typeof AuthorizedDefaultAclRulesRoute
  '/settings/client': typeof AuthorizedDefaultSettingsClientRoute
  '/settings/edit-openid': typeof AuthorizedDefaultSettingsEditOpenidRoute
  '/settings/gateway-notifications': typeof AuthorizedDefaultSettingsGatewayNotificationsRoute
  '/settings/instance': typeof AuthorizedDefaultSettingsInstanceRoute
  '/settings/ldap': typeof AuthorizedDefaultSettingsLdapRoute
  '/settings/openid': typeof AuthorizedDefaultSettingsOpenidRoute
  '/settings/smtp': typeof AuthorizedDefaultSettingsSmtpRoute
  '/user/$username': typeof AuthorizedDefaultUserUsernameRoute
  '/vpn-overview/$locationId': typeof AuthorizedDefaultVpnOverviewLocationIdRoute
  '/locations': typeof AuthorizedDefaultLocationsIndexRoute
  '/settings': typeof AuthorizedDefaultSettingsIndexRoute
  '/vpn-overview': typeof AuthorizedDefaultVpnOverviewIndexRoute
  '/edge/$edgeId/edit': typeof AuthorizedDefaultEdgeEdgeIdEditRoute
  '/locations/$locationId/edit': typeof AuthorizedDefaultLocationsLocationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/consent': typeof ConsentRoute
  '/snackbar': typeof SnackbarRoute
  '/_authorized/_default': typeof AuthorizedDefaultRouteWithChildren
  '/_authorized/playground': typeof AuthorizedPlaygroundRoute
  '/_wizard/setup': typeof WizardSetupRoute
  '/_wizard/setup-login': typeof WizardSetupLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/loading': typeof AuthLoadingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_authorized/_default/activity': typeof AuthorizedDefaultActivityRoute
  '/_authorized/_default/edges': typeof AuthorizedDefaultEdgesRoute
  '/_authorized/_default/groups': typeof AuthorizedDefaultGroupsRoute
  '/_authorized/_default/network-devices': typeof AuthorizedDefaultNetworkDevicesRoute
  '/_authorized/_default/openid': typeof AuthorizedDefaultOpenidRoute
  '/_authorized/_default/users': typeof AuthorizedDefaultUsersRoute
  '/_authorized/_default/webhooks': typeof AuthorizedDefaultWebhooksRoute
  '/_authorized/_wizard/add-external-openid': typeof AuthorizedWizardAddExternalOpenidRoute
  '/_authorized/_wizard/add-location': typeof AuthorizedWizardAddLocationRoute
  '/_authorized/_wizard/setup-edge': typeof AuthorizedWizardSetupEdgeRoute
  '/_authorized/_wizard/setup-gateway': typeof AuthorizedWizardSetupGatewayRoute
  '/auth/mfa/email': typeof AuthMfaEmailRoute
  '/auth/mfa/recovery': typeof AuthMfaRecoveryRoute
  '/auth/mfa/totp': typeof AuthMfaTotpRoute
  '/auth/mfa/webauthn': typeof AuthMfaWebauthnRoute
  '/_authorized/_default/acl/add-alias': typeof AuthorizedDefaultAclAddAliasRoute
  '/_authorized/_default/acl/add-destination': typeof AuthorizedDefaultAclAddDestinationRoute
  '/_authorized/_default/acl/add-rule': typeof AuthorizedDefaultAclAddRuleRoute
  '/_authorized/_default/acl/aliases': typeof AuthorizedDefaultAclAliasesRoute
  '/_authorized/_default/acl/destinations': typeof AuthorizedDefaultAclDestinationsRoute
  '/_authorized/_default/acl/edit-alias': typeof AuthorizedDefaultAclEditAliasRoute
  '/_authorized/_default/acl/edit-destination': typeof AuthorizedDefaultAclEditDestinationRoute
  '/_authorized/_default/acl/edit-rule': typeof AuthorizedDefaultAclEditRuleRoute
  '/_authorized/_default/acl/rules': typeof AuthorizedDefaultAclRulesRoute
  '/_authorized/_default/settings/client': typeof AuthorizedDefaultSettingsClientRoute
  '/_authorized/_default/settings/edit-openid': typeof AuthorizedDefaultSettingsEditOpenidRoute
  '/_authorized/_default/settings/gateway-notifications': typeof AuthorizedDefaultSettingsGatewayNotificationsRoute
  '/_authorized/_default/settings/instance': typeof AuthorizedDefaultSettingsInstanceRoute
  '/_authorized/_default/settings/ldap': typeof AuthorizedDefaultSettingsLdapRoute
  '/_authorized/_default/settings/openid': typeof AuthorizedDefaultSettingsOpenidRoute
  '/_authorized/_default/settings/smtp': typeof AuthorizedDefaultSettingsSmtpRoute
  '/_authorized/_default/user/$username': typeof AuthorizedDefaultUserUsernameRoute
  '/_authorized/_default/vpn-overview/$locationId': typeof AuthorizedDefaultVpnOverviewLocationIdRoute
  '/_authorized/_default/locations/': typeof AuthorizedDefaultLocationsIndexRoute
  '/_authorized/_default/settings/': typeof AuthorizedDefaultSettingsIndexRoute
  '/_authorized/_default/vpn-overview/': typeof AuthorizedDefaultVpnOverviewIndexRoute
  '/_authorized/_default/edge/$edgeId/edit': typeof AuthorizedDefaultEdgeEdgeIdEditRoute
  '/_authorized/_default/locations/$locationId/edit': typeof AuthorizedDefaultLocationsLocationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/auth'
    | '/consent'
    | '/snackbar'
    | '/playground'
    | '/setup'
    | '/setup-login'
    | '/auth/callback'
    | '/auth/loading'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/'
    | '/activity'
    | '/edges'
    | '/groups'
    | '/network-devices'
    | '/openid'
    | '/users'
    | '/webhooks'
    | '/add-external-openid'
    | '/add-location'
    | '/setup-edge'
    | '/setup-gateway'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
    | '/acl/add-alias'
    | '/acl/add-destination'
    | '/acl/add-rule'
    | '/acl/aliases'
    | '/acl/destinations'
    | '/acl/edit-alias'
    | '/acl/edit-destination'
    | '/acl/edit-rule'
    | '/acl/rules'
    | '/settings/client'
    | '/settings/edit-openid'
    | '/settings/gateway-notifications'
    | '/settings/instance'
    | '/settings/ldap'
    | '/settings/openid'
    | '/settings/smtp'
    | '/user/$username'
    | '/vpn-overview/$locationId'
    | '/locations/'
    | '/settings/'
    | '/vpn-overview/'
    | '/edge/$edgeId/edit'
    | '/locations/$locationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/'
    | '/consent'
    | '/snackbar'
    | '/playground'
    | '/setup'
    | '/setup-login'
    | '/auth/callback'
    | '/auth/loading'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth'
    | '/activity'
    | '/edges'
    | '/groups'
    | '/network-devices'
    | '/openid'
    | '/users'
    | '/webhooks'
    | '/add-external-openid'
    | '/add-location'
    | '/setup-edge'
    | '/setup-gateway'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
    | '/acl/add-alias'
    | '/acl/add-destination'
    | '/acl/add-rule'
    | '/acl/aliases'
    | '/acl/destinations'
    | '/acl/edit-alias'
    | '/acl/edit-destination'
    | '/acl/edit-rule'
    | '/acl/rules'
    | '/settings/client'
    | '/settings/edit-openid'
    | '/settings/gateway-notifications'
    | '/settings/instance'
    | '/settings/ldap'
    | '/settings/openid'
    | '/settings/smtp'
    | '/user/$username'
    | '/vpn-overview/$locationId'
    | '/locations'
    | '/settings'
    | '/vpn-overview'
    | '/edge/$edgeId/edit'
    | '/locations/$locationId/edit'
  id:
    | '__root__'
    | '/404'
    | '/_authorized'
    | '/auth'
    | '/consent'
    | '/snackbar'
    | '/_authorized/_default'
    | '/_authorized/playground'
    | '/_wizard/setup'
    | '/_wizard/setup-login'
    | '/auth/callback'
    | '/auth/loading'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/'
    | '/_authorized/_default/activity'
    | '/_authorized/_default/edges'
    | '/_authorized/_default/groups'
    | '/_authorized/_default/network-devices'
    | '/_authorized/_default/openid'
    | '/_authorized/_default/users'
    | '/_authorized/_default/webhooks'
    | '/_authorized/_wizard/add-external-openid'
    | '/_authorized/_wizard/add-location'
    | '/_authorized/_wizard/setup-edge'
    | '/_authorized/_wizard/setup-gateway'
    | '/auth/mfa/email'
    | '/auth/mfa/recovery'
    | '/auth/mfa/totp'
    | '/auth/mfa/webauthn'
    | '/_authorized/_default/acl/add-alias'
    | '/_authorized/_default/acl/add-destination'
    | '/_authorized/_default/acl/add-rule'
    | '/_authorized/_default/acl/aliases'
    | '/_authorized/_default/acl/destinations'
    | '/_authorized/_default/acl/edit-alias'
    | '/_authorized/_default/acl/edit-destination'
    | '/_authorized/_default/acl/edit-rule'
    | '/_authorized/_default/acl/rules'
    | '/_authorized/_default/settings/client'
    | '/_authorized/_default/settings/edit-openid'
    | '/_authorized/_default/settings/gateway-notifications'
    | '/_authorized/_default/settings/instance'
    | '/_authorized/_default/settings/ldap'
    | '/_authorized/_default/settings/openid'
    | '/_authorized/_default/settings/smtp'
    | '/_authorized/_default/user/$username'
    | '/_authorized/_default/vpn-overview/$locationId'
    | '/_authorized/_default/locations/'
    | '/_authorized/_default/settings/'
    | '/_authorized/_default/vpn-overview/'
    | '/_authorized/_default/edge/$edgeId/edit'
    | '/_authorized/_default/locations/$locationId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  SnackbarRoute: typeof SnackbarRoute
  WizardSetupRoute: typeof WizardSetupRoute
  WizardSetupLoginRoute: typeof WizardSetupLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snackbar': {
      id: '/snackbar'
      path: '/snackbar'
      fullPath: '/snackbar'
      preLoaderRoute: typeof SnackbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/loading': {
      id: '/auth/loading'
      path: '/loading'
      fullPath: '/auth/loading'
      preLoaderRoute: typeof AuthLoadingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_wizard/setup-login': {
      id: '/_wizard/setup-login'
      path: '/setup-login'
      fullPath: '/setup-login'
      preLoaderRoute: typeof WizardSetupLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wizard/setup': {
      id: '/_wizard/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof WizardSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/playground': {
      id: '/_authorized/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthorizedPlaygroundRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/_default': {
      id: '/_authorized/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedDefaultRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/auth/mfa/webauthn': {
      id: '/auth/mfa/webauthn'
      path: '/webauthn'
      fullPath: '/auth/mfa/webauthn'
      preLoaderRoute: typeof AuthMfaWebauthnRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/totp': {
      id: '/auth/mfa/totp'
      path: '/totp'
      fullPath: '/auth/mfa/totp'
      preLoaderRoute: typeof AuthMfaTotpRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/recovery': {
      id: '/auth/mfa/recovery'
      path: '/recovery'
      fullPath: '/auth/mfa/recovery'
      preLoaderRoute: typeof AuthMfaRecoveryRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/auth/mfa/email': {
      id: '/auth/mfa/email'
      path: '/email'
      fullPath: '/auth/mfa/email'
      preLoaderRoute: typeof AuthMfaEmailRouteImport
      parentRoute: typeof AuthMfaRoute
    }
    '/_authorized/_wizard/setup-gateway': {
      id: '/_authorized/_wizard/setup-gateway'
      path: '/setup-gateway'
      fullPath: '/setup-gateway'
      preLoaderRoute: typeof AuthorizedWizardSetupGatewayRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/_wizard/setup-edge': {
      id: '/_authorized/_wizard/setup-edge'
      path: '/setup-edge'
      fullPath: '/setup-edge'
      preLoaderRoute: typeof AuthorizedWizardSetupEdgeRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/_wizard/add-location': {
      id: '/_authorized/_wizard/add-location'
      path: '/add-location'
      fullPath: '/add-location'
      preLoaderRoute: typeof AuthorizedWizardAddLocationRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/_wizard/add-external-openid': {
      id: '/_authorized/_wizard/add-external-openid'
      path: '/add-external-openid'
      fullPath: '/add-external-openid'
      preLoaderRoute: typeof AuthorizedWizardAddExternalOpenidRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_authorized/_default/webhooks': {
      id: '/_authorized/_default/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthorizedDefaultWebhooksRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/users': {
      id: '/_authorized/_default/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthorizedDefaultUsersRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/openid': {
      id: '/_authorized/_default/openid'
      path: '/openid'
      fullPath: '/openid'
      preLoaderRoute: typeof AuthorizedDefaultOpenidRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/network-devices': {
      id: '/_authorized/_default/network-devices'
      path: '/network-devices'
      fullPath: '/network-devices'
      preLoaderRoute: typeof AuthorizedDefaultNetworkDevicesRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/groups': {
      id: '/_authorized/_default/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthorizedDefaultGroupsRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/edges': {
      id: '/_authorized/_default/edges'
      path: '/edges'
      fullPath: '/edges'
      preLoaderRoute: typeof AuthorizedDefaultEdgesRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/activity': {
      id: '/_authorized/_default/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthorizedDefaultActivityRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/vpn-overview/': {
      id: '/_authorized/_default/vpn-overview/'
      path: '/vpn-overview'
      fullPath: '/vpn-overview/'
      preLoaderRoute: typeof AuthorizedDefaultVpnOverviewIndexRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/': {
      id: '/_authorized/_default/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthorizedDefaultSettingsIndexRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/locations/': {
      id: '/_authorized/_default/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthorizedDefaultLocationsIndexRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/vpn-overview/$locationId': {
      id: '/_authorized/_default/vpn-overview/$locationId'
      path: '/vpn-overview/$locationId'
      fullPath: '/vpn-overview/$locationId'
      preLoaderRoute: typeof AuthorizedDefaultVpnOverviewLocationIdRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/user/$username': {
      id: '/_authorized/_default/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AuthorizedDefaultUserUsernameRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/smtp': {
      id: '/_authorized/_default/settings/smtp'
      path: '/settings/smtp'
      fullPath: '/settings/smtp'
      preLoaderRoute: typeof AuthorizedDefaultSettingsSmtpRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/openid': {
      id: '/_authorized/_default/settings/openid'
      path: '/settings/openid'
      fullPath: '/settings/openid'
      preLoaderRoute: typeof AuthorizedDefaultSettingsOpenidRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/ldap': {
      id: '/_authorized/_default/settings/ldap'
      path: '/settings/ldap'
      fullPath: '/settings/ldap'
      preLoaderRoute: typeof AuthorizedDefaultSettingsLdapRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/instance': {
      id: '/_authorized/_default/settings/instance'
      path: '/settings/instance'
      fullPath: '/settings/instance'
      preLoaderRoute: typeof AuthorizedDefaultSettingsInstanceRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/gateway-notifications': {
      id: '/_authorized/_default/settings/gateway-notifications'
      path: '/settings/gateway-notifications'
      fullPath: '/settings/gateway-notifications'
      preLoaderRoute: typeof AuthorizedDefaultSettingsGatewayNotificationsRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/edit-openid': {
      id: '/_authorized/_default/settings/edit-openid'
      path: '/settings/edit-openid'
      fullPath: '/settings/edit-openid'
      preLoaderRoute: typeof AuthorizedDefaultSettingsEditOpenidRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/settings/client': {
      id: '/_authorized/_default/settings/client'
      path: '/settings/client'
      fullPath: '/settings/client'
      preLoaderRoute: typeof AuthorizedDefaultSettingsClientRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/rules': {
      id: '/_authorized/_default/acl/rules'
      path: '/acl/rules'
      fullPath: '/acl/rules'
      preLoaderRoute: typeof AuthorizedDefaultAclRulesRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/edit-rule': {
      id: '/_authorized/_default/acl/edit-rule'
      path: '/acl/edit-rule'
      fullPath: '/acl/edit-rule'
      preLoaderRoute: typeof AuthorizedDefaultAclEditRuleRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/edit-destination': {
      id: '/_authorized/_default/acl/edit-destination'
      path: '/acl/edit-destination'
      fullPath: '/acl/edit-destination'
      preLoaderRoute: typeof AuthorizedDefaultAclEditDestinationRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/edit-alias': {
      id: '/_authorized/_default/acl/edit-alias'
      path: '/acl/edit-alias'
      fullPath: '/acl/edit-alias'
      preLoaderRoute: typeof AuthorizedDefaultAclEditAliasRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/destinations': {
      id: '/_authorized/_default/acl/destinations'
      path: '/acl/destinations'
      fullPath: '/acl/destinations'
      preLoaderRoute: typeof AuthorizedDefaultAclDestinationsRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/aliases': {
      id: '/_authorized/_default/acl/aliases'
      path: '/acl/aliases'
      fullPath: '/acl/aliases'
      preLoaderRoute: typeof AuthorizedDefaultAclAliasesRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/add-rule': {
      id: '/_authorized/_default/acl/add-rule'
      path: '/acl/add-rule'
      fullPath: '/acl/add-rule'
      preLoaderRoute: typeof AuthorizedDefaultAclAddRuleRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/add-destination': {
      id: '/_authorized/_default/acl/add-destination'
      path: '/acl/add-destination'
      fullPath: '/acl/add-destination'
      preLoaderRoute: typeof AuthorizedDefaultAclAddDestinationRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/acl/add-alias': {
      id: '/_authorized/_default/acl/add-alias'
      path: '/acl/add-alias'
      fullPath: '/acl/add-alias'
      preLoaderRoute: typeof AuthorizedDefaultAclAddAliasRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/locations/$locationId/edit': {
      id: '/_authorized/_default/locations/$locationId/edit'
      path: '/locations/$locationId/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof AuthorizedDefaultLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
    '/_authorized/_default/edge/$edgeId/edit': {
      id: '/_authorized/_default/edge/$edgeId/edit'
      path: '/edge/$edgeId/edit'
      fullPath: '/edge/$edgeId/edit'
      preLoaderRoute: typeof AuthorizedDefaultEdgeEdgeIdEditRouteImport
      parentRoute: typeof AuthorizedDefaultRoute
    }
  }
}

interface AuthorizedDefaultRouteChildren {
  AuthorizedDefaultActivityRoute: typeof AuthorizedDefaultActivityRoute
  AuthorizedDefaultEdgesRoute: typeof AuthorizedDefaultEdgesRoute
  AuthorizedDefaultGroupsRoute: typeof AuthorizedDefaultGroupsRoute
  AuthorizedDefaultNetworkDevicesRoute: typeof AuthorizedDefaultNetworkDevicesRoute
  AuthorizedDefaultOpenidRoute: typeof AuthorizedDefaultOpenidRoute
  AuthorizedDefaultUsersRoute: typeof AuthorizedDefaultUsersRoute
  AuthorizedDefaultWebhooksRoute: typeof AuthorizedDefaultWebhooksRoute
  AuthorizedDefaultAclAddAliasRoute: typeof AuthorizedDefaultAclAddAliasRoute
  AuthorizedDefaultAclAddDestinationRoute: typeof AuthorizedDefaultAclAddDestinationRoute
  AuthorizedDefaultAclAddRuleRoute: typeof AuthorizedDefaultAclAddRuleRoute
  AuthorizedDefaultAclAliasesRoute: typeof AuthorizedDefaultAclAliasesRoute
  AuthorizedDefaultAclDestinationsRoute: typeof AuthorizedDefaultAclDestinationsRoute
  AuthorizedDefaultAclEditAliasRoute: typeof AuthorizedDefaultAclEditAliasRoute
  AuthorizedDefaultAclEditDestinationRoute: typeof AuthorizedDefaultAclEditDestinationRoute
  AuthorizedDefaultAclEditRuleRoute: typeof AuthorizedDefaultAclEditRuleRoute
  AuthorizedDefaultAclRulesRoute: typeof AuthorizedDefaultAclRulesRoute
  AuthorizedDefaultSettingsClientRoute: typeof AuthorizedDefaultSettingsClientRoute
  AuthorizedDefaultSettingsEditOpenidRoute: typeof AuthorizedDefaultSettingsEditOpenidRoute
  AuthorizedDefaultSettingsGatewayNotificationsRoute: typeof AuthorizedDefaultSettingsGatewayNotificationsRoute
  AuthorizedDefaultSettingsInstanceRoute: typeof AuthorizedDefaultSettingsInstanceRoute
  AuthorizedDefaultSettingsLdapRoute: typeof AuthorizedDefaultSettingsLdapRoute
  AuthorizedDefaultSettingsOpenidRoute: typeof AuthorizedDefaultSettingsOpenidRoute
  AuthorizedDefaultSettingsSmtpRoute: typeof AuthorizedDefaultSettingsSmtpRoute
  AuthorizedDefaultUserUsernameRoute: typeof AuthorizedDefaultUserUsernameRoute
  AuthorizedDefaultVpnOverviewLocationIdRoute: typeof AuthorizedDefaultVpnOverviewLocationIdRoute
  AuthorizedDefaultLocationsIndexRoute: typeof AuthorizedDefaultLocationsIndexRoute
  AuthorizedDefaultSettingsIndexRoute: typeof AuthorizedDefaultSettingsIndexRoute
  AuthorizedDefaultVpnOverviewIndexRoute: typeof AuthorizedDefaultVpnOverviewIndexRoute
  AuthorizedDefaultEdgeEdgeIdEditRoute: typeof AuthorizedDefaultEdgeEdgeIdEditRoute
  AuthorizedDefaultLocationsLocationIdEditRoute: typeof AuthorizedDefaultLocationsLocationIdEditRoute
}

const AuthorizedDefaultRouteChildren: AuthorizedDefaultRouteChildren = {
  AuthorizedDefaultActivityRoute: AuthorizedDefaultActivityRoute,
  AuthorizedDefaultEdgesRoute: AuthorizedDefaultEdgesRoute,
  AuthorizedDefaultGroupsRoute: AuthorizedDefaultGroupsRoute,
  AuthorizedDefaultNetworkDevicesRoute: AuthorizedDefaultNetworkDevicesRoute,
  AuthorizedDefaultOpenidRoute: AuthorizedDefaultOpenidRoute,
  AuthorizedDefaultUsersRoute: AuthorizedDefaultUsersRoute,
  AuthorizedDefaultWebhooksRoute: AuthorizedDefaultWebhooksRoute,
  AuthorizedDefaultAclAddAliasRoute: AuthorizedDefaultAclAddAliasRoute,
  AuthorizedDefaultAclAddDestinationRoute:
    AuthorizedDefaultAclAddDestinationRoute,
  AuthorizedDefaultAclAddRuleRoute: AuthorizedDefaultAclAddRuleRoute,
  AuthorizedDefaultAclAliasesRoute: AuthorizedDefaultAclAliasesRoute,
  AuthorizedDefaultAclDestinationsRoute: AuthorizedDefaultAclDestinationsRoute,
  AuthorizedDefaultAclEditAliasRoute: AuthorizedDefaultAclEditAliasRoute,
  AuthorizedDefaultAclEditDestinationRoute:
    AuthorizedDefaultAclEditDestinationRoute,
  AuthorizedDefaultAclEditRuleRoute: AuthorizedDefaultAclEditRuleRoute,
  AuthorizedDefaultAclRulesRoute: AuthorizedDefaultAclRulesRoute,
  AuthorizedDefaultSettingsClientRoute: AuthorizedDefaultSettingsClientRoute,
  AuthorizedDefaultSettingsEditOpenidRoute:
    AuthorizedDefaultSettingsEditOpenidRoute,
  AuthorizedDefaultSettingsGatewayNotificationsRoute:
    AuthorizedDefaultSettingsGatewayNotificationsRoute,
  AuthorizedDefaultSettingsInstanceRoute:
    AuthorizedDefaultSettingsInstanceRoute,
  AuthorizedDefaultSettingsLdapRoute: AuthorizedDefaultSettingsLdapRoute,
  AuthorizedDefaultSettingsOpenidRoute: AuthorizedDefaultSettingsOpenidRoute,
  AuthorizedDefaultSettingsSmtpRoute: AuthorizedDefaultSettingsSmtpRoute,
  AuthorizedDefaultUserUsernameRoute: AuthorizedDefaultUserUsernameRoute,
  AuthorizedDefaultVpnOverviewLocationIdRoute:
    AuthorizedDefaultVpnOverviewLocationIdRoute,
  AuthorizedDefaultLocationsIndexRoute: AuthorizedDefaultLocationsIndexRoute,
  AuthorizedDefaultSettingsIndexRoute: AuthorizedDefaultSettingsIndexRoute,
  AuthorizedDefaultVpnOverviewIndexRoute:
    AuthorizedDefaultVpnOverviewIndexRoute,
  AuthorizedDefaultEdgeEdgeIdEditRoute: AuthorizedDefaultEdgeEdgeIdEditRoute,
  AuthorizedDefaultLocationsLocationIdEditRoute:
    AuthorizedDefaultLocationsLocationIdEditRoute,
}

const AuthorizedDefaultRouteWithChildren =
  AuthorizedDefaultRoute._addFileChildren(AuthorizedDefaultRouteChildren)

interface AuthorizedRouteChildren {
  AuthorizedDefaultRoute: typeof AuthorizedDefaultRouteWithChildren
  AuthorizedPlaygroundRoute: typeof AuthorizedPlaygroundRoute
  AuthorizedWizardAddExternalOpenidRoute: typeof AuthorizedWizardAddExternalOpenidRoute
  AuthorizedWizardAddLocationRoute: typeof AuthorizedWizardAddLocationRoute
  AuthorizedWizardSetupEdgeRoute: typeof AuthorizedWizardSetupEdgeRoute
  AuthorizedWizardSetupGatewayRoute: typeof AuthorizedWizardSetupGatewayRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedDefaultRoute: AuthorizedDefaultRouteWithChildren,
  AuthorizedPlaygroundRoute: AuthorizedPlaygroundRoute,
  AuthorizedWizardAddExternalOpenidRoute:
    AuthorizedWizardAddExternalOpenidRoute,
  AuthorizedWizardAddLocationRoute: AuthorizedWizardAddLocationRoute,
  AuthorizedWizardSetupEdgeRoute: AuthorizedWizardSetupEdgeRoute,
  AuthorizedWizardSetupGatewayRoute: AuthorizedWizardSetupGatewayRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

interface AuthMfaRouteChildren {
  AuthMfaEmailRoute: typeof AuthMfaEmailRoute
  AuthMfaRecoveryRoute: typeof AuthMfaRecoveryRoute
  AuthMfaTotpRoute: typeof AuthMfaTotpRoute
  AuthMfaWebauthnRoute: typeof AuthMfaWebauthnRoute
}

const AuthMfaRouteChildren: AuthMfaRouteChildren = {
  AuthMfaEmailRoute: AuthMfaEmailRoute,
  AuthMfaRecoveryRoute: AuthMfaRecoveryRoute,
  AuthMfaTotpRoute: AuthMfaTotpRoute,
  AuthMfaWebauthnRoute: AuthMfaWebauthnRoute,
}

const AuthMfaRouteWithChildren =
  AuthMfaRoute._addFileChildren(AuthMfaRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoadingRoute: typeof AuthLoadingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoadingRoute: AuthLoadingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AuthorizedRoute: AuthorizedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConsentRoute: ConsentRoute,
  SnackbarRoute: SnackbarRoute,
  WizardSetupRoute: WizardSetupRoute,
  WizardSetupLoginRoute: WizardSetupLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
