name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Individual Contributor Assignment Agreement and I hereby sign the Individual Contributor Assignment Agreement') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_SIGNATURES_REPO_PAT }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/DefGuard/defguard/blob/stable/2.x/CLA.md'
          remote-organization-name: 'DefGuard'
          remote-repository-name: 'cla-signatures'
          branch: 'main'
          allowlist: bot*,dependabot[bot],filipslezaklab,j-chmielewski,jacobdefguard,jakub-tldr,kchudy,mike767,moubctez,t-aleksander,teon,Va1ter,wojcik91
