on:
  push:
    branches:
      - dev
      - 'release/**'
      - 'stable/**'
    paths:
      - "e2e/**"
  pull_request:
    branches:
      - dev
      - 'release/**'
      - 'stable/**'
    paths:
      - "e2e/**"

jobs:
  lint-e2e:
    runs-on:
      - codebuild-defguard-core-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10

      # Change to '--frozen-lockfile' once this gets fixed:
      # https://github.com/pnpm/action-setup/issues/40
      - name: Build and lint e2e
        working-directory: e2e
        run: |
          pnpm install --no-frozen-lockfile
          pnpm lint
