on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    paths:
      - "e2e/**"
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
    paths:
      - "e2e/**"

jobs:
  lint-e2e:
    runs-on:
      - codebuild-defguard-core-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      # Change to '--frozen-lockfile' once this gets fixed:
      # https://github.com/pnpm/action-setup/issues/40
      - name: Build and lint e2e
        working-directory: e2e
        run: |
          pnpm install --no-frozen-lockfile
          pnpm lint
