name: Make a new release
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  build-docker-release:
    # Ignore tags with -, like v1.0.0-alpha
    # This job will build the docker container with the "latest" tag which
    # is a tag used in production, thus it should only be run for full releases.
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-')
    name: Build Release Docker image
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha
      # Explicitly disable latest tag. It will be added otherwise.
      flavor: |
        latest=false

  build-docker-prerelease:
    # Only build tags with -, like v1.0.0-alpha
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-')
    name: Build Pre-release Docker image
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=raw,value=pre-release
        type=semver,pattern={{version}}
        type=sha
      # Explicitly disable latest tag. It will be added otherwise.
      flavor: |
        latest=false

  create-release:
    name: create-release
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        id: release
        uses: shogo82148/actions-create-release@6a396031bc74c57403da1018fec74d24c6aa03cd # v1
        with:
          draft: true
          generate_release_notes: true

  create-sbom:
    needs:
      - create-release
      - build-docker-release
    uses: ./.github/workflows/sbom.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-binaries:
    needs:
      - create-release
    runs-on:
      - self-hosted
      - Linux
      - X64
    env:
      SQLX_OFFLINE: "1"
      # Force the installed stable toolchain. RUSTUP_TOOLCHAIN takes precedence
      # over any stale rustup directory override left on the self-hosted runner.
      RUSTUP_TOOLCHAIN: "stable"
      # sccache
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0.4.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: web/package.json

      - name: Build frontend
        working-directory: web
        run: |
          pnpm install --ignore-scripts --frozen-lockfile
          pnpm build

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          targets: "aarch64-unknown-linux-gnu"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Build Linux x86_64 binary
        run: |
          cargo build --locked --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/defguard defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu
          tar -zcf defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz \
            defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu

      - name: Build Linux aarch64 binary
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          PKG_CONFIG_SYSROOT_DIR: /usr/lib/aarch64-linux-gnu
        run: |
          cargo build --locked --release --target aarch64-unknown-linux-gnu
          mv target/aarch64-unknown-linux-gnu/release/defguard defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu
          tar -zcf defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.tar.gz \
            defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu

      - name: Build FreeBSD binary
        run: |
          rsync -rlptxzH -e 'ssh -l root' --del ./ freebsd:work/defguard/
          ssh root@freebsd 'cd work/defguard && cargo build --locked --release'
          scp root@freebsd:work/defguard/target/release/defguard defguard-${{ env.VERSION }}-x86_64-unknown-freebsd
          tar -zcf defguard-${{ env.VERSION }}-x86_64-unknown-freebsd.tar.gz \
            defguard-${{ env.VERSION }}-x86_64-unknown-freebsd

      - name: Build x86_64 DEB package
        uses: defGuard/fpm-action@ebb2575fbb892876fbdd326bb6d12524fbd7398c # main
        with:
          fpm_args:
            "defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu=/usr/bin/defguard
            linux/defguard.service=/usr/lib/systemd/system/defguard.service
            .env.example=/etc/defguard/core.conf"
          fpm_opts:
            "--architecture amd64
            --output-type deb
            --version ${{ env.VERSION }}
            --package defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.deb
            --before-install linux/preinst
            --after-install linux/postinst
            --before-remove linux/prerm
            --after-remove linux/postrm"

      - name: Build aarch64 DEB package
        uses: defGuard/fpm-action@ebb2575fbb892876fbdd326bb6d12524fbd7398c # main
        with:
          fpm_args:
            "defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu=/usr/bin/defguard
            linux/defguard.service=/usr/lib/systemd/system/defguard.service
            .env.example=/etc/defguard/core.conf"
          fpm_opts:
            "--architecture arm64
            --output-type deb
            --version ${{ env.VERSION }}
            --package defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.deb
            --before-install linux/preinst
            --after-install linux/postinst
            --before-remove linux/prerm
            --after-remove linux/postrm"

      - name: Build x86_64 RPM package
        uses: defGuard/fpm-action@ebb2575fbb892876fbdd326bb6d12524fbd7398c # main
        with:
          fpm_args:
            "defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu=/usr/bin/defguard
            linux/defguard.service=/usr/lib/systemd/system/defguard.service
            .env.example=/etc/defguard/core.conf"
          fpm_opts:
            "--architecture amd64
            --output-type rpm
            --version ${{ env.VERSION }}
            --package defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.rpm
            --before-install linux/preinst
            --after-install linux/postinst
            --before-remove linux/prerm
            --after-remove linux/postrm"

      - name: Build aarch64 RPM package
        uses: defGuard/fpm-action@ebb2575fbb892876fbdd326bb6d12524fbd7398c # main
        with:
          fpm_args:
            "defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu=/usr/bin/defguard
            linux/defguard.service=/usr/lib/systemd/system/defguard.service
            .env.example=/etc/defguard/core.conf"
          fpm_opts:
            "--architecture arm64
            --output-type rpm
            --version ${{ env.VERSION }}
            --package defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.rpm
            --before-install linux/preinst
            --after-install linux/postinst
            --before-remove linux/prerm
            --after-remove linux/postrm"

      - name: Build FreeBSD package
        uses: defGuard/fpm-action@ebb2575fbb892876fbdd326bb6d12524fbd7398c # main
        with:
          fpm_args:
            "defguard-${{ env.VERSION }}-x86_64-unknown-freebsd=/usr/local/bin/defguard
            freebsd/defguard=/usr/local/etc/rc.d/defguard
            .env.example=/etc/defguard/core.conf.sample"
          fpm_opts:
            "--architecture amd64
            --output-type freebsd
            --version ${{ env.VERSION }}
            --package defguard-${{ env.VERSION }}_x86_64-unknown-freebsd.pkg
            --freebsd-osversion '*'
            --depends openssl
            --after-install freebsd/post-install.sh"

      - name: Upload Linux x86_64 archive
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload Linux aarch64 archive
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.tar.gz
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload FreeBSD x86_64 archive
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-x86_64-unknown-freebsd.tar.gz
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload Linux x86_64 DEB
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.deb
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload Linux aarch64 DEB
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.deb
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload Linux x86_64 RPM
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-x86_64-unknown-linux-gnu.rpm
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload Linux aarch64 RPM
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-aarch64-unknown-linux-gnu.rpm
          asset_content_type: application/gzip
          overwrite: true

      - name: Upload FreeBSD package
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}_x86_64-unknown-freebsd.pkg
          asset_content_type: application/x-pkg
          overwrite: true

  ubuntu-22-04-build:
    needs:
      - create-release
    runs-on:
      - self-hosted
      - Linux
      - ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        architecture: [ARM64, X64]
        include:
          - architecture: ARM64
            deb_arch: arm64
            rust_target: aarch64-unknown-linux-gnu
          - architecture: X64
            deb_arch: amd64
            rust_target: x86_64-unknown-linux-gnu
    container:
      image: ubuntu:22.04
      env:
        DEBIAN_FRONTEND: noninteractive
        HOME: /root
        RUSTUP_HOME: /root/.rustup
        CARGO_HOME: /root/.cargo

    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git curl ca-certificates libatomic1
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: web/package.json

      - name: Build frontend
        working-directory: web
        run: |
          pnpm install --ignore-scripts --frozen-lockfile
          pnpm build

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

      - name: Install build dependencies
        run: |
          apt-get install -y \
            build-essential pkg-config \
            libssl-dev \
            protobuf-compiler libprotobuf-dev \
            ruby ruby-dev rubygems rpm
          gem install fpm --no-document

      - name: Build binary
        run: |
          cargo build --locked --release --target ${{ matrix.rust_target }}

      - name: Build DEB package (ubuntu-22-04-lts)
        run: |
          fpm \
            --output-type deb \
            --version "${{ env.VERSION }}" \
            --architecture ${{ matrix.deb_arch }} \
            --package defguard-${{ env.VERSION }}-${{ matrix.deb_arch }}_ubuntu-22-04-lts.deb \
            --before-install linux/preinst \
            --after-install linux/postinst \
            --before-remove linux/prerm \
            --after-remove linux/postrm \
            "target/${{ matrix.rust_target }}/release/defguard=/usr/bin/defguard" \
            "linux/defguard.service=/usr/lib/systemd/system/defguard.service" \
            ".env.example=/etc/defguard/core.conf"

      - name: Upload ubuntu-22-04-lts DEB
        uses: shogo82148/actions-upload-release-asset@394b3c11c3cfc038b5396ad265c074065cf875c3 # v1.10.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}-${{ matrix.deb_arch }}_ubuntu-22-04-lts.deb
          asset_content_type: application/gzip
          overwrite: true
