minimumReleaseAge: 2880
overrides:
  isbot: "5.1.42"
  seroval: ">=1.4.1"
  launch-editor: ">=2.14.1"
  js-yaml@<4.2.0: ">=4.2.0"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
minimumReleaseAgeExclude:
  # Renovate security update: humanize-duration@3.34.0
  - humanize-duration@3.34.0
