allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@tanstack/form-core@1.33.0'
  - '@tanstack/react-form@1.33.0'
  - '@tanstack/react-router@1.170.9'
  - '@tanstack/react-virtual@3.13.26'
  - '@tanstack/router-core@1.171.7'
  - '@tanstack/router-generator@1.167.11'
  - '@tanstack/router-plugin@1.168.12'
  - '@tanstack/virtual-core@3.16.0'
  - dayjs@1.11.21
  - zustand@5.0.14
  - '@tanstack/react-virtual@3.14.3'
  - '@tanstack/virtual-core@3.17.1'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
