allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@tanstack/form-core@1.33.0'
  - '@tanstack/react-form@1.33.0'
  - '@tanstack/react-router@1.170.9'
  - '@tanstack/router-core@1.171.7'
  - '@tanstack/router-generator@1.167.11'
  - '@tanstack/router-plugin@1.168.12'
  - zustand@5.0.14

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
